---
web:
  port: 80
storage:
  type: postgres
  path: postgres://${SECRET_PGADMIN_USER}:${SECRET_PGADMIN_PASSWORD}@postgres16-rw.database.svc.cluster.local:5432/gatus?sslmode=disable
  caching: true
metrics: true
debug: false
ui:
  title: sensei chess service status
  header: sensei chess service status
  logo: "https://senseichess.com/static/images/hero.png"
alerting:
  discord:
    webhook-url: ${SECRET_SENSE_DISCORD_WEBHOOK}
    default-alert:
      description: healthcheck failed
      send-on-resolved: true
      failure-threshold: 3
      success-threshold: 5
connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m
endpoints:
  ## services
  - name: sensei frontend
    group: sensei
    url: https://www.${SECRET_DOMAIN_TWO}
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: discord
        description: "healthcheck failed"
        send-on-resolved: true
              
  - name: sensei backend
    group: sensei
    url: https://api.${SECRET_DOMAIN_TWO}
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: discord
        description: "healthcheck failed"
        send-on-resolved: true

  ## Services  
  - name: postgresql
    group: services
    url: "tcp://192.168.3.42:5432"
    interval: 1m
    ui:
      hide-hostname: true
      hide-url: true
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: discord
        description: "healthcheck failed"
        send-on-resolved: true

  - name: langfuse
    group: services
    url: https://langfuse.${SECRET_DOMAIN_TWO}
    interval: 1m
    ui:
      hide-hostname: true
      hide-url: true    
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: discord
        description: "healthcheck failed"
        send-on-resolved: true