apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-restore
spec:
  superuserSecret:
    name: cloudnative-pg-secrets
  bootstrap:
    recovery:
      source: &previousCluster postgres16-v1
  # Note: externalClusters is needed when recovering from an existing cnpg cluster
  externalClusters:
    - name: *previousCluster
      barmanObjectStore: &barmanObjectStore
        data:
          compression: bzip2
        wal:
          compression: bzip2
          maxParallel: 8
        destinationPath: s3://cloudnative-pg/
        #endpointURL: https://s3.${SECRET_DOMAIN}
        endpointURL: http://minio.kube-system.svc.cluster.local:9000    
      
        s3Credentials:
          accessKeyId:
            name: cloudnative-pg-secrets
            key: AWS_ACCESS_KEY_ID
          secretAccessKey:
            name: cloudnative-pg-secrets
            key: AWS_SECRET_ACCESS_KEY
      
