---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app nfs-server
  namespace: default
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 30m

  values:
    controllers:
      nfs-server-share1:
        replicas: 1
        containers:
          app:
            image:
              repository: izdock/nfs-ganesha
              tag: 4.0.12-3
            env:
              EXPORT_PATH: /exports/share1
              PSEUDO_PATH: /share1
              CLIENT_LIST: 0.0.0.0/0
              SQUASH_MODE: No_Root_Squash
              ACCESS_TYPE: RW
              LOG_LEVEL: INFO
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi
      nfs-server-share2:
        replicas: 1
        containers:
          app:
            image:
              repository: izdock/nfs-ganesha
              tag: 4.0.12-3
            env:
              EXPORT_PATH: /exports/share2
              PSEUDO_PATH: /share2
              CLIENT_LIST: 0.0.0.0/0
              SQUASH_MODE: No_Root_Squash
              ACCESS_TYPE: RW
              LOG_LEVEL: INFO
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi
      nfs-server-share3:
        replicas: 1
        containers:
          app:
            image:
              repository: izdock/nfs-ganesha
              tag: 4.0.12-3
            env:
              EXPORT_PATH: /exports/share3
              PSEUDO_PATH: /share3
              CLIENT_LIST: 0.0.0.0/0
              SQUASH_MODE: No_Root_Squash
              ACCESS_TYPE: RW
              LOG_LEVEL: INFO
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi
    service:
      share1:
        controller: nfs-server-share1
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 192.168.3.36
        ports:
          nfs:
            port: 2049
            protocol: TCP
          nfs-udp:
            port: 2049
            protocol: UDP
          mountd:
            port: 20048
            protocol: TCP
          mountd-udp:
            port: 20048
            protocol: UDP
          rpcbind:
            port: 111
            protocol: TCP
          rpcbind-udp:
            port: 111
            protocol: UDP
      share2:
        controller: nfs-server-share2
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 192.168.3.37
        ports:
          nfs:
            port: 2049
            protocol: TCP
          nfs-udp:
            port: 2049
            protocol: UDP
          mountd:
            port: 20048
            protocol: TCP
          mountd-udp:
            port: 20048
            protocol: UDP
          rpcbind:
            port: 111
            protocol: TCP
          rpcbind-udp:
            port: 111
            protocol: UDP
      share3:
        controller: nfs-server-share3
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 192.168.3.38
        ports:
          nfs:
            port: 2049
            protocol: TCP
          nfs-udp:
            port: 2049
            protocol: UDP
          mountd:
            port: 20048
            protocol: TCP
          mountd-udp:
            port: 20048
            protocol: UDP
          rpcbind:
            port: 111
            protocol: TCP
          rpcbind-udp:
            port: 111
            protocol: UDP
    persistence:
      share1:
        enabled: true
        existingClaim: nfs-server-share1
        advancedMounts:
          nfs-server-share1:
            app:
              - path: /exports/share1
      share2:
        enabled: true
        existingClaim: nfs-server-share2
        advancedMounts:
          nfs-server-share2:
            app:
              - path: /exports/share2
      share3:
        enabled: true
        existingClaim: nfs-server-share3
        advancedMounts:
          nfs-server-share3:
            app:
              - path: /exports/share3
