---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-logical-restore-target
  namespace: database
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.3-7
  enableSuperuserAccess: true
  bootstrap:
    initdb:
      database: logical_restore_control
      owner: logical_restore_control
  postgresql:
    shared_preload_libraries:
      - pg_stat_statements
  storage:
    size: 50Gi
    storageClass: ceph-block
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 4Gi
