apiVersion: batch/v1
kind: CronJob
metadata:
  name: sensei-dev-daily-refresh
  namespace: sensei
spec:
  schedule: "0 1 * * *" # 1AM every day
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: sensei-secret
          containers:
            - name: dev-daily-user-refresh
              image: ghcr.io/clarknova99/project-sensei/backend:dev-latest@sha256:4303221ac4b09451d478cb6902ec8a497cd1c7ffa0f9ee2096c2e91dae5a0ee6
              imagePullPolicy: Always
              command: ["/bin/sh", "-c", "python3 /app/daily_refresh.py"]
              env:
                - name: PG_URI
                  value: postgresql://${SECRET_SENSEI_USERNAME}:${SECRET_SENSEI_PASSWORD}@postgres16vector-rw.database.svc.cluster.local:5432/sensei-dev
                - name: LANGFUSE_PUBLIC_KEY
                  value: ${SECRET_LANGFUSE_PUBLIC_KEY}
                - name: LANGFUSE_SECRET_KEY
                  value: ${SECRET_LANGFUSE_SECRET_KEY}
                - name: LANGFUSE_HOST
                  value: http://langfuse-v3-web.sensei.svc.cluster.local:3000
                - name: GROQ_API_KEY_LLM
                  valueFrom:
                    secretKeyRef:
                      name: sensei-prod-daily-refresh-secrets
                      key: GROQ_API_KEY_LLM
                - name: GROQ_API_KEY_PGN_TEXT
                  valueFrom:
                    secretKeyRef:
                      name: sensei-prod-daily-refresh-secrets
                      key: GROQ_API_KEY_PGN_TEXT
                - name: LITELLM_BASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: sensei-prod-daily-refresh-secrets
                      key: LITELLM_BASE_URL
                - name: LITELLM_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: sensei-prod-daily-refresh-secrets
                      key: LITELLM_API_KEY
                # - name: PG_URI
                #   valueFrom:
                #     secretKeyRef:
                #       name: sensei-prod-daily-refresh-secrets
                #       key: PG_URI
                - name: DISCORD_WEBHOOK
                  valueFrom:
                    secretKeyRef:
                      name: sensei-prod-daily-refresh-secrets
                      key: DISCORD_WEBHOOK
                - name: LICHESS_API_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: sensei-prod-daily-refresh-secrets
                      key: LICHESS_API_TOKEN
                - name: ENVIRONMENT
                  value: "dev"
          restartPolicy: OnFailure
