apiVersion: v1
kind: Secret
metadata:
    name: sensei-secret
    namespace: sensei
type: kubernetes.io/dockerconfigjson
## sops --encrypt --in-place ./kubernetes/apps/default/sensei/app/sensei.sops.yaml
## sops --decrypt ./kubernetes/apps/default/sensei/app/sensei.sops.yaml | kubectl apply -f -
data:
    .dockerconfigjson: ENC[AES256_GCM,data:iXM7gvqEt1mRnHyVmuMLFw7WRuyDYkgyXO5CrBUF5IP16dHPE0pqa6N4XzOB65SVnM+0Ic3ayAnMGsAtVuctbjc/XEcZyelSWU7gs+UmD2zZwNfUe1djBBsJ7zLk8iNhq7j5FpqRWG9a/aa2HjHyTfQxzzVFHgLzKkvEzoTCITgDvgS5TguOrzpwKy9jL3Fdglwcw4miaSzFiv5n3tbOyIR+uSSWtSshzMTuTd7VJs9uWSs6N7SptAUOxOWUbAJdY0w4lW/UtvjQ+yPtxHR0RF/1DLgmiUWRLCIkS/z+20DFqqGmt0CFl8qAJAt01SFwqRGIIvzfN9+DoD3jNZhnEHo2xFsu4abuK8rYQV8Tyv9/lXLxguGCLveizkcNPagW,iv:iM2M5IvPi5k9ZcEh/CPQFmnsYerLZdggw/Xu24DBdns=,tag:bdPTiPfDRSsdID4jzbxsGw==,type:str]
sops:
    age:
        - recipient: age1q6l62kwaly44pl9vwedqvxtxv0fsndtq53s6kzclsccslne7cpfs2352vr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5YkQxdFBIVWh0eWtaeVZ6
            ZGtVUE85WFdCNktSK2pmUmVlZW95V1NpTFhJCklrWXFsbHdSVVpVcEpOTUdlR0I3
            MDdYcUdlT044VjhmMFFpL2lQR0ZUbTQKLS0tIFhtdTRsdFozK3VqajdiZDNrcGZF
            OUpsalBnM01VaFM5blQxZXNhblV3WUUKoHDxccQBoUt15TGbs8JLMVgdZFVAvRAD
            SYFJNXWQgHbZIyOXSr3uDWvmP4BG9zzLOb5t+EosSZu3Iup6C2vzPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-03T01:58:11Z"
    mac: ENC[AES256_GCM,data:pptuKUpF7Esg1ubfFNfaCIETTlvwSvF+RhtnCY4Y4X7TAb2ZZIilW4rzkORD054k8/A5IRvMaZ+4Ev/plHD+N9Xv164choYO2uE7GOZCcCc3EUwdPvRkxsNjFvYWgt5KTumkWcLsk6TMxgZc116DCjasP3omEF4XuRNdGTrDnlw=,iv:gvg+wVhwLLPmy9srfp2qd4nskNYCEVP8sVIxfmGTfbg=,tag:c2y4vqhx68CNEcWfcvaojQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
