# ---
# apiVersion: helm.toolkit.fluxcd.io/v2
# kind: HelmRelease
# metadata:
#   name: k8s-gateway
# spec:
#   interval: 30m
#   chart:
#     spec:
#       chart: k8s-gateway
#       version: 2.4.0
#       sourceRef:
#         kind: HelmRepository
#         name: k8s-gateway
#         namespace: flux-system
#   install:
#     remediation:
#       retries: 3
#   upgrade:
#     cleanupOnFail: true
#     remediation:
#       retries: 3
#   values:
#     fullnameOverride: k8s-gateway
#     domain: "${SECRET_DOMAIN} ${SECRET_DOMAIN_TWO}"
#     ttl: 1
#     service:
#       type: LoadBalancer
#       port: 53
#       annotations:
#         io.cilium/lb-ipam-ips: "192.168.3.22"
#       externalTrafficPolicy: Cluster
#     watchedResources: ["Ingress", "Service"]

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: k8s-gateway
  namespace: network # Required for Renovate lookups
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 3.2.6
  url: oci://ghcr.io/k8s-gateway/charts/k8s-gateway
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app k8s-gateway
  namespace: network
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: k8s-gateway
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    # image:
    #   registry: ghcr.io
    #   repository: k8s-gateway/k8s_gateway
    #   tag: 1.2.0
    #   pullPolicy: IfNotPresent
    fullnameOverride: k8s-gateway
    watchedResources: ["Ingress", "Service","HTTPRoute"]
    domain: "${SECRET_DOMAIN} ${SECRET_DOMAIN_TWO}"
    ttl: 1
    service:
      type: LoadBalancer
      port: 53
      annotations:
        io.cilium/lb-ipam-ips: "192.168.3.22"
      externalTrafficPolicy: Cluster
