apiVersion: v1
kind: Secret
metadata:
    name: invidious-secrets
## sops --encrypt --in-place ./kubernetes/apps/media/invidious/app/inv.sops.yaml
## sops --decrypt ./kubernetes/apps/media/invidious/app/inv.sops.yaml | kubectl apply -f -
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:wvfHVoqvZ0rz,iv:XSQyyPgXZDO0mJ8xgdTEFKPAXIY4HDVQP7/Xp6rCwE0=,tag:564bYvSQ2xZDc4ktX35DtA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:bpNDjYHL7BZFqf2/a1yI1jghxmiMNts6hu9CdyjCJBfUthRVJGM7PA==,iv:2f00/SHtKHdhOurq3D4doE3pUC8Yjn1cQpGdzMnYcsI=,tag:URHJIlxrnmaLYJ9onEg4HQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:7UxPmznQnHs=,iv:43yBfLcWMbs8uZJqMKExiYyhWkYQWkUwuV+muT3gEOo=,tag:twPm69MmFM2mgKjSzkCu+w==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:dAgq02WfFuoz,iv:EORHDQ+aNUT5bfjA/F7Z7kour0Hj9A56TRpmhnsCD/8=,tag:MrqQ7pZoaWkp98WUbjtCHw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:JXC568Igih0K,iv:ChNaz3l+pqvSdCbVY/TqLQEV0DK05FO3Bfns1I4UkMI=,tag:P1MCKWYx0kRF8dfQNZG5pA==,type:str]
    INVIDIOUS_CONFIG: ENC[AES256_GCM,data:nNEAYphjxLeWser7tKbVU2BxSDj50qp7lJFNrWm3JbmnAiiYROMcAfZvPdv4/80UfSADPeCwhiXV/pgqYG5EKWDGoV/ttxTyr8ZyRfS8wgJARtCNWGWrKzK9hhU/I2j7L7diDkd1gVXOr0aDIpnDtj8dK/h/pU7aVMAQb2wojkoExMK+Cx0l72JUPG8HQdE/AnshcHxIbod9yoa86fyVX7ru4gwKgx4mH/ASQ7thbOSavNMHIhIiQrn4KEZaWyZLUUiuMon0Lms1EbuQxlPzx580yoTUB8YwgVNNv+dDdSnf+RaAvxbxbEgg6SEuo+JrSHWpv8fAQZHNnN8KABRGCO2nXYC+JfUrZR/DqPkHp0mPSFpXaDEV1RVLDLqlUJ1nM/VJxcsC/E5MshQ0HlIX,iv:67RCJhh+xv94hrwO4hx8F92gsX9Mp9gCd+K0xYOruQo=,tag:TGNPnK64khAC5nbjOLy1gg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q6l62kwaly44pl9vwedqvxtxv0fsndtq53s6kzclsccslne7cpfs2352vr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1NTdadFFueGhUcy8yZUNj
            ampzOERRczcwWTBnWnhtS0pDRU55V2RDYUQ0Cmx0L1J2cDFreWxTazlqeERvaTMv
            RW5DaGsvaXJEMHNLaHFyYmpSdmlubkEKLS0tIFhYLysyV25oemI5WXpmYitWWlVs
            cVNHMGY0aEhMQUNIN1JNY1I1UEUrYzAKawZFtq0WCeE3tiVD+ESFlFcYwUqfLRft
            wg6xMXq0VJ4aaHSR5TPSVeHLYKiW0DY290uz8G8XsAaSXte8h7gtxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-11T15:06:50Z"
    mac: ENC[AES256_GCM,data:hdOcwUBSwtwlf4FrtFW5mdmmdEztHaUGIdmut26kdWIYCg2vAXTRmtB19cSD+s7AqKo/adoNJdeyXwsfUEGpWPGOWkNIQ88WEc5vADsZJwftgroaoCWuiMPm4h6cLMYfCTjd2pOAIaj12cQ057k20l84UHzqimxOxLAydAVybs4=,iv:PZb/6XbGRObYo5D6GJolYYSgl2PmiIRkZcK99frk3Fs=,tag:I93xgmTZGKeJp6E/nPd6CQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
