apiVersion: v1
kind: Secret
metadata:
    name: ghost-secrets
    namespace: sensei
## sops --encrypt --in-place ./kubernetes/apps/sensei/sensei-prod/blog/ghost.sops.yaml
## sops --decrypt ./kubernetes/apps/sensei/sensei-prod/blog/ghost.sops.yaml | kubectl apply -f -
stringData:
    GHOST_DB_ROOT_PASSWORD: ENC[AES256_GCM,data:SZxhOVON,iv:B7Tvv2w3gw66g8DfHdZ3qjACj1ymTQ9jKWq2k8tFvnM=,tag:7G1KZkEp/ow5U1Q5lHyw6w==,type:str]
    GHOST_DB_PASSWORD: ENC[AES256_GCM,data:h1sK1STE,iv:RrNLh2AiKCblTsH7l8XLwlazRiYGSMqKuw+PBwJkRnM=,tag:PkeQ4VuSef2PdfWvJnyAcQ==,type:str]
    GHOST_DB_USER: ENC[AES256_GCM,data:49lDrLMd,iv:2lTV+DxxxvZ/1LdlaR10+FU7N9YBuGsdsdaB7KAu680=,tag:XjgN6LWoFmiWscOaJNmlIg==,type:str]
    GHOST_DB_DB: ENC[AES256_GCM,data:ypx4DFfn,iv:+S9JSpqPj1zeq9RFuhEXaAwLLsukzLve0gBnZQ+PfJc=,tag:fZ/RGwVOWKRCbJ8sG3KEjA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q6l62kwaly44pl9vwedqvxtxv0fsndtq53s6kzclsccslne7cpfs2352vr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5YkQxdFBIVWh0eWtaeVZ6
            ZGtVUE85WFdCNktSK2pmUmVlZW95V1NpTFhJCklrWXFsbHdSVVpVcEpOTUdlR0I3
            MDdYcUdlT044VjhmMFFpL2lQR0ZUbTQKLS0tIFhtdTRsdFozK3VqajdiZDNrcGZF
            OUpsalBnM01VaFM5blQxZXNhblV3WUUKoHDxccQBoUt15TGbs8JLMVgdZFVAvRAD
            SYFJNXWQgHbZIyOXSr3uDWvmP4BG9zzLOb5t+EosSZu3Iup6C2vzPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-14T03:59:08Z"
    mac: ENC[AES256_GCM,data:VJSaTnbX3QnLnZz4TvuEOzJhJu6+jA+mN4QhE6t4jfVub4jL0mFvDzjDV7jYyxt1QgJHl6TXSqHwJMUP2dPj6k5iJO14KmZwI8TTDb5mWsNg292/ve3a0xliFKJhxTPSrBaavqX9/p4NIq+lEIncJE3BkM7lpMkrFxcY4AZUxV0=,iv:PCy2vW/t2glb0B8YQd4yRx7brsfkcSLeX2LrekyyUAA=,tag:tbUkzLWfgf2/2RrWIy/N4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
