---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ghost-mariadb
spec:
  interval: 15m
  chart:
    spec:
      chart: mariadb
      version: 19.1.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 15m
  values:
    auth:
      rootPassword: ${SECRET_GHOST_DB_ROOT_PASSWORD}
      username: ${SECRET_GHOST_DB_USER}
      password: ${SECRET_GHOST_DB_PASSWORD}
      database: ${SECRET_GHOST_DB_DB}
    primary:
      persistence:
        existingClaim: ghost-mariadb