---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1h
  url: "https://github.com/clarknova99/talos-cluster.git"
  ref:
    branch: "main"
