---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: omni
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      omni:
        #type: deployment
        containers:
          app:
            image:
              repository: ghcr.io/siderolabs/omni
              tag: v0.49.1
            args:
              - --name=omni
              - --account-id=538BEBF8-105F-40E8-8E4C-0DFA1ACEE326
              - --siderolink-use-grpc-tunnel=true
              - --private-key-source='file:///secrets/omni.asc'
              - --machine-api-bind-addr=0.0.0.0:8090
              - --k8s-proxy-bind-addr=0.0.0.0:8100
              - --advertised-api-url=https://omni.${SECRET_DOMAIN}
              - --advertised-kubernetes-proxy-url=https://omni-k8s.${SECRET_DOMAIN}
              - --siderolink-api-advertised-url=https://omni-api.${SECRET_DOMAIN}
              - --auth-auth0-enabled=true
              - --auth-auth0-domain=${SECRET_OMNI_AUTH0_DOMAIN}
              - --auth-auth0-client-id=${SECRET_OMNI_AUTH0_CLIENT_ID}
              - --initial-users=${SECRET_OMNI_INITIAL_USERS}
              - --debug
            securityContext:
              allowPrivilegeEscalation: true
              capabilities:
                add:
                  - NET_ADMIN
                  - SYS_ADMIN
              readOnlyRootFilesystem: false
              privileged: true
    service:
      app:
        controller: omni
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          io.cilium/lb-ipam-ips: 192.168.3.89
        ports:
          http:
            port: 80
          https:
            port: 443
          event-sink:
            port: 8091
          siderolink-api:
            port: 8090
          k8s-proxy:
            port: 8100

    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          hajimari.io/enable: "true"
          hajimari.io/icon: mdi:math-compass
        className: internal
        hosts:
          - host: omni.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: 443
          - host: omni-api.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: 8090                   
          - host: omni-k8s.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: 8100
        tls:
          - hosts:
              - omni.${SECRET_DOMAIN}
              - omni-api.${SECRET_DOMAIN}
              - omni-k8s.${SECRET_DOMAIN}
    persistence:
      dev-net-tun:
        type: hostPath
        hostPath: /dev/net/tun
      etcd:
        enabled: true
        type: nfs
        server: 192.168.1.3
        path: /volume1/network-storage/cluster/omni/etcd
        globalMounts:
          - path: /_out/etcd
      config:
        enabled: true
        type: nfs
        server: 192.168.1.3
        path: /volume1/network-storage/cluster/omni
        globalMounts:
          - path: /
      secrets:
        type: secret
        name: omni-secrets
      # tls-key:
      #   enabled: true
      #   type: nfs
      #   server: 192.168.1.2
      #   path: /volume1/network-storage/omni/tls.key
      #   globalMounts:
      #     - path: /tls.key
      # omni-asc:
      #   enabled: true
      #   type: nfs
      #   server: 192.168.1.2
      #   path: /volume1/network-storage/omni/omni.asc
      #   globalMounts:
      #     - path: /omni.asc
