{
 "title": "Global Kubernetes Overview",
 "tags": [
  "Kubernetes",
  "Prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Global Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Global CPU  Usage",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum by (instance, cpu) (rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\"}[$__rate_interval])))",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"}) / sum(machine_cpu_cores{})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\"}) / sum(machine_cpu_cores{})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Global RAM Usage",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{} - node_memory_MemAvailable_bytes{}) / sum(node_memory_MemTotal_bytes{})",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"}) / sum(machine_memory_bytes{})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\"}) / sum(machine_memory_bytes{})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count by (node) (kube_node_info{}))"
    }
   ]
  },
  {
   "title": "Cluster CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(sum by (instance, cpu) (rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\"}[$__rate_interval])))",
     "legendFormat": "CPU usage in %"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Cluster Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{} - node_memory_MemAvailable_bytes{}) / sum(node_memory_MemTotal_bytes{})",
     "legendFormat": "Memory usage in %"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(machine_cpu_cores{})", "legendFormat": "Total" },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\"}[$__rate_interval]))",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(machine_memory_bytes{})", "legendFormat": "Total" },
    {
     "expr": "sum(node_memory_MemTotal_bytes{} - node_memory_MemAvailable_bytes{})",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"})",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Namespaces",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_namespace_created{})"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "CPU Utilization by namespace",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Memory Utilization by namespace",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\"}) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Global Network Utilization by device",
   "type": "timeseries",
   "description": "Dropped noisy virtual devices for readability.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!~\"lxc.*|veth.*\"}[$__rate_interval]))",
     "legendFormat": "Received : {{ device }}"
    },
    {
     "expr": "- sum(rate(node_network_transmit_bytes_total{device!~\"lxc.*|veth.*\"}[$__rate_interval]))",
     "legendFormat": "Transmitted : {{ device }}"
    }
   ]
  },
  {
   "title": "Sensei Kubernetes Resource Count",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_namespace_labels{namespace=\"sensei\"})",
     "legendFormat": "Namespaces"
    },
    {
     "expr": "sum(kube_pod_container_status_running{namespace=\"sensei\"})",
     "legendFormat": "Running Containers"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\", namespace=\"sensei\"})",
     "legendFormat": "Running Pods"
    },
    {
     "expr": "sum(kube_service_info{namespace=\"sensei\"})",
     "legendFormat": "Services"
    },
    {
     "expr": "sum(kube_endpoint_info{namespace=\"sensei\"})",
     "legendFormat": "Endpoints"
    },
    {
     "expr": "sum(kube_ingress_info{namespace=\"sensei\"})",
     "legendFormat": "Ingresses"
    },
    {
     "expr": "sum(kube_deployment_labels{cluster=\"$cluster\"})",
     "legendFormat": "Deployments"
    },
    {
     "expr": "sum(kube_statefulset_labels{namespace=\"sensei\"})",
     "legendFormat": "Statefulsets"
    },
    {
     "expr": "sum(kube_daemonset_labels{cluster=\"$cluster\"})",
     "legendFormat": "Daemonsets"
    },
    {
     "expr": "sum(kube_persistentvolumeclaim_info{namespace=\"sensei\"})",
     "legendFormat": "Persistent Volume Claims"
    },
    {
     "expr": "sum(kube_hpa_labels{namespace=\"sensei\"})",
     "legendFormat": "Horizontal Pod Autoscalers"
    },
    {
     "expr": "sum(kube_configmap_info{namespace=\"sensei\"})",
     "legendFormat": "Configmaps"
    },
    {
     "expr": "sum(kube_secret_info{namespace=\"sensei\"})",
     "legendFormat": "Secrets"
    },
    {
     "expr": "sum(kube_networkpolicy_labels{namespace=\"sensei\"})",
     "legendFormat": "Network Policies"
    },
    {
     "expr": "count(count by (node) (kube_node_info{namespace=\"sensei\"}))",
     "legendFormat": "Nodes"
    }
   ]
  },
  {
   "title": "Sensei Container Restarts",
   "type": "barchart",
   "description": "No data is generally a good thing here.",
   "gridPos": { "h": 13, "w": 13, "x": 10, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=\"sensei\"}[$__rate_interval])) by (namespace) > 0",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } }
 ]
}