{
 "title": "Sensei Logs",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "New panel",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "app:=\"sensei-dev-api\" | fields module, function, level"
    }
   ]
  },
  {
   "title": "Log Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(\n  count_over_time({app=\"sensei-prod-api\"} |= \"[API]\" |= \"ERROR\" [5m])\n)",
     "legendFormat": "error"
    },
    {
     "expr": "sum(\n  count_over_time({app=\"sensei-prod-api\"} |= \"[API]\" |= \"INFO\" [5m])\n)",
     "legendFormat": "info"
    }
   ]
  },
  {
   "title": "Backend Logs - PROD",
   "type": "logs",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"sensei-prod-api\"} \n| json \n| label_format original_line=\"{{__line__}}\"\n| line_format \"{{.level | ToUpper}} [{{.module}}:{{.function}}] {{if .path}}path={{.path}}{{end}} {{if .sensei_user_id}}user={{.sensei_user_id}}{{end}} {{if .status_code}}status={{.status_code}}{{end}} {{if .duration_ms}}duration={{.duration_ms}}ms{{end}} msg={{.msg}}\" "
    }
   ]
  },
  {
   "title": "Frontend Logs - PROD",
   "type": "logs",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 26 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"sensei-prod-app\"} \n| json \n| label_format original_line=\"{{__line__}}\"\n| line_format \"{{.level | ToUpper}} [{{.module}}:{{.function}}] {{if .path}}path={{.path}}{{end}} {{if .sensei_user_id}}user={{.sensei_user_id}}{{end}} {{if .status_code}}status={{.status_code}}{{end}} {{if .duration_ms}}duration={{.duration_ms}}ms{{end}} msg={{.msg}}\" "
    }
   ]
  },
  {
   "title": "Worker Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 35 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"sensei-prod-worker\"} \n| json \n| label_format original_line=\"{{__line__}}\"\n| line_format \"{{.level | ToUpper}} [{{.module}}:{{.function}}] {{if .path}}path={{.path}}{{end}} {{if .sensei_user_id}}user={{.sensei_user_id}}{{end}} {{if .status_code}}status={{.status_code}}{{end}} {{if .duration_ms}}duration={{.duration_ms}}ms{{end}} msg={{.msg}}\" "
    }
   ]
  },
  {
   "title": "Backend Logs - DEV",
   "type": "logs",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 44 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"sensei-dev-api\"} "
    }
   ]
  },
  {
   "title": "Frontend Logs - DEV",
   "type": "logs",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 54 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"sensei-dev-app\"} |= `` | logfmt"
    }
   ]
  },
  {
   "title": "Backend Logs - STAGE",
   "type": "logs",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 63 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"sensei-stage-api\"} "
    }
   ]
  },
  {
   "title": "Frontend Logs - STAGE",
   "type": "logs",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 73 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"sensei-stage-app\"} |= `` | logfmt"
    }
   ]
  },
  {
   "title": "Worker Stage Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 82 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"sensei-stage-worker\"}"
    }
   ]
  },
  {
   "title": "Daily Prod Refresh Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 91 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"sensei-prod-daily-refresh\"}"
    }
   ]
  },
  {
   "title": "Daily Stage Refresh Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 100 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"sensei-stage-daily-refresh\"}"
    }
   ]
  },
  {
   "title": "Ingress Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 109 },
   "targets": [
    {
     "expr": "{instance=\"ingress-nginx-external\"} |= `` | json | __error__=`` | vhost =~ `senseichess.com` | line_format `[{{.status}}] {{.http_x_forwarded_for}} - {{.http_user_agent}} - {{.city_name}}, {{.country_name}} - {{.path}} - {{.request_query}}` | label_format level=detected_level"
    }
   ]
  },
  {
   "title": "Request Status Codes",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
   "targets": [
    {
     "expr": "sum(\n  count_over_time({instance=\"ingress-nginx-external\"} \n  | json \n  | country_name != \"\"\n  | status != \"\" \n  | status != \"200\"\n  [24h])\n\n) by (country_name, status)"
    }
   ]
  }
 ]
}