---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1beta1.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sensei
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: posthog-scripts
    files:
    - bin/build-schema-json.mjs
    - bin/build-schema-python.sh
    - bin/celery-queues.env
    - bin/check_kafka_clickhouse_up
    - bin/check_temporal_up
    - bin/copy-posthog-js
    - bin/deploy-hobby
    - bin/docker
    - bin/docker-backend
    - bin/docker-dev
    - bin/docker-dev-web
    - bin/docker-frontend
    - bin/docker-migrate
    - bin/docker-server
    - bin/docker-server-unit
    - bin/docker-worker
    - bin/docker-worker-beat
    - bin/docker-worker-celery
    - bin/e2e-test-runner
    - bin/hobby-ci.py
    - bin/hog
    - bin/hoge
    - bin/install-macosx_arm64
    - bin/migrate
    - bin/migrate-check
    - bin/migrate_kafka_data.py
    - bin/mprocs.yaml
    - bin/plugin-server
    - bin/start
    - bin/start-backend
    - bin/start-celery
    - bin/start-cyclotron
    - bin/start-frontend
    - bin/start-worker
    - bin/temporal-django-worker
    - bin/tests
    - bin/unit_metrics.py
    - bin/upgrade-hobby
generatorOptions:
  disableNameSuffixHash: true