---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: kite
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kite
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: kite
    namespace: default
# ---
# apiVersion: talos.dev/v1alpha1
# kind: ServiceAccount
# metadata:
#   name: kite
# spec:
#   roles: ["os:admin"]
