apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:kvchk9aM50a6t6EqVCTtBrqQp52U9i74fm0Mr9Kxe9TfkrQB,iv:zPLEawfUjxNCYmH7gh4GSv2bZc0CIEX9tjsDIDq3vh0=,tag:I3PS6JiXw4sUDQNMbvzSLg==,type:str]
    credentials.json: ENC[AES256_GCM,data:izt/SAgrltLrfUAUgjcujn3En+CA+cm2RStFJWzd0K1vhpwY6QBgn8DIx0p33QZ+BzWp/TSxnGAszZshc4rJ/7ngqA6YsBE9ib1QvShSSPhu+dkq0EI5ivq1NDEScVR1XveqSLw+JRnKvz90EXoSTIzOdODVNMdkPDveyAxWpeSIrDdPhN9+UySlqdOSs74Ll3wkhBkN+Dn+1KsOJAeg5clNKJX982Ql04wb+i4XTg==,iv:vesy8TbztiZ0j54ON+fOCp8BLXI17v6gaQ31S1wwjaM=,tag:Gg5vFhbkNg9XMPHnjSTERQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q6l62kwaly44pl9vwedqvxtxv0fsndtq53s6kzclsccslne7cpfs2352vr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZVFLWVFsT2dUc080SEl5
            VTlneWZyQ2ZudHJSdVlXd3NjY1FycFdpWUZNCnl2RFlWZklETDFGbDRJYkVLczdN
            N1hUOGlHWVU5QXdwL1pwc2ZsRHRLa2cKLS0tIEFMMmMyT3hiNHd3cWR5a0lsdG02
            MU9lYUJPdkRpSCt6bW10N1FzTjdxcTQK/hLjxFg2l1ZK1Yc4NfPt/Tkmm1uNcEK+
            dGm1JhevDUy/FNfAmPjbv1DwbpHOjv42T10Zfd1hkbhEGihLziZCBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-04T04:33:27Z"
    mac: ENC[AES256_GCM,data:Zo1bqVowtDXDqjQdEELR0r8dnWiYgLUp3vecvu3dNFmOwEP/awhgTxlrTDc/fqt5uVPOOHXvhwMaLoDtdJRT5tYjPzDA+xt6ZMTOiRjkFDNo1duC7/5z1rEKhoEayrGZueQCbj5aR40BK9qL1DhNf3/KyAcHOQAZvTOgw7+FRQA=,iv:ijEaWLsYVBIpxOtNTPi29FwGqikwQX/JQw+KS8QwY+I=,tag:0WPqokiD+ggMuaLFZtfKrw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
