{
 "title": "Ingress Logs",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "geomap",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (lat, lon, city_name, geoip_country_code, vhost) (count_over_time({instance=\"ingress-nginx-external\"} \n| json \n| lat != \"\"\n|__error__=``[$__range]))",
     "legendFormat": "{{ip_address}}"
    }
   ]
  },
  {
   "title": "Unique Visitors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (http_x_forwarded_for) (count_over_time({instance=\"ingress-nginx-external\"} | json  |  __error__=\"\" [$__range])))"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({instance=\"ingress-nginx-external\"} | json  |  __error__=\"\" [$__range]))"
    }
   ]
  },
  {
   "title": "Requests by Location",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (city_name, country_code) (count_over_time({instance=\"ingress-nginx-external\"} | json | city_name != \"\" |  __error__=\"\" [24h]))",
     "legendFormat": "{{city_name}} {{country_code}}"
    }
   ]
  },
  {
   "title": "Requests by Host",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (vhost) (count_over_time({instance=\"ingress-nginx-external\"} | json | vhost != \"\" |  __error__=\"\" [24h]))",
     "legendFormat": "{{vhost}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "{instance=\"ingress-nginx-external\"} \n|= `` \n| json \n| __error__=`` \n| line_format `[{{.status}}] {{.vhost}} - {{.http_x_forwarded_for}} - {{.user_agent}} - {{.city_name}}, {{.geoip_country_code}} - {{.path}} - {{.request_query}}`"
    }
   ]
  }
 ]
}