{
 "title": "Temperatures",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "mercury",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(node_hwmon_temp_celsius{instance=\"192.168.3.241:9100\", chip=\"platform_coretemp_0\", sensor=\"temp1\"}[$__interval])",
     "legendFormat": "CPU"
    },
    {
     "expr": "avg_over_time(node_hwmon_temp_celsius{instance=\"192.168.3.241:9100\", chip=\"nvme_nvme0\", sensor=\"temp1\"}[$__interval])",
     "legendFormat": "NVME"
    },
    {
     "expr": "node_hwmon_temp_celsius{instance=\"192.168.3.241:9100\", chip=\"thermal_thermal_zone0\", sensor=\"temp0\"}",
     "legendFormat": "SYSTEM"
    }
   ]
  },
  {
   "title": "venus",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(node_hwmon_temp_celsius{instance=\"192.168.3.101:9100\", chip=\"platform_coretemp_0\", sensor=\"temp1\"}[$__interval])  ",
     "legendFormat": "CPU"
    },
    {
     "expr": "avg_over_time(node_hwmon_temp_celsius{instance=\"192.168.3.101:9100\", chip=\"nvme_nvme0\", sensor=\"temp1\"}[$__interval])",
     "legendFormat": "NVME"
    },
    {
     "expr": "node_hwmon_temp_celsius{instance=\"192.168.3.101:9100\", chip=\"thermal_thermal_zone0\", sensor=\"temp0\"}",
     "legendFormat": "SYSTEM"
    }
   ]
  },
  {
   "title": "earth",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(node_hwmon_temp_celsius{instance=\"192.168.3.214:9100\", chip=\"platform_coretemp_0\", sensor=\"temp1\"}[$__interval])",
     "legendFormat": "CPU"
    },
    {
     "expr": "avg_over_time(node_hwmon_temp_celsius{instance=\"192.168.3.214:9100\", chip=\"nvme_nvme0\", sensor=\"temp1\"}[$__interval])",
     "legendFormat": "NVME"
    },
    {
     "expr": "node_hwmon_temp_celsius{instance=\"192.168.3.214:9100\", chip=\"thermal_thermal_zone0\", sensor=\"temp0\"}",
     "legendFormat": "SYSTEM"
    }
   ]
  },
  {
   "title": "mars",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(node_hwmon_temp_celsius{instance=\"192.168.3.102:9100\", chip=\"platform_coretemp_0\", sensor=\"temp1\"}[$__interval])",
     "legendFormat": "CPU"
    },
    {
     "expr": "avg_over_time(node_hwmon_temp_celsius{instance=\"192.168.3.102:9100\", chip=\"nvme_nvme0\", sensor=\"temp1\"}[$__interval])",
     "legendFormat": "NVME"
    },
    {
     "expr": "node_hwmon_temp_celsius{instance=\"192.168.3.102:9100\", chip=\"thermal_thermal_zone0\", sensor=\"temp2\"}",
     "legendFormat": "SYSTEM"
    }
   ]
  },
  {
   "title": "jupiter",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 7, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(node_hwmon_temp_celsius{instance=\"192.168.3.219:9100\", chip=\"platform_coretemp_0\", sensor=\"temp1\"}[$__interval])  ",
     "legendFormat": "CPU"
    },
    {
     "expr": "avg_over_time(node_hwmon_temp_celsius{instance=\"192.168.3.219:9100\", chip=\"nvme_nvme0\", sensor=\"temp1\"}[$__interval])   ",
     "legendFormat": "NVME"
    },
    {
     "expr": "node_hwmon_temp_celsius{instance=\"192.168.3.219:9100\", chip=\"thermal_thermal_zone0\", sensor=\"temp2\"}    ",
     "legendFormat": "SYSTEM"
    }
   ]
  }
 ]
}