---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
resources:
  - ./rbac.yaml
  - ./postgres16.yaml
  - ./postgres16vector.yaml
configMapGenerator:
  - name: cnpg-logical-backup-scripts
    files:
      - backup.sh
      - orchestrate.sh
      - worker-job.yaml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
