apiVersion: v1
kind: Secret
metadata:
    name: sensei-secret
    namespace: sensei
type: kubernetes.io/dockerconfigjson
## sops --encrypt --in-place ./kubernetes/apps/default/sensei/app/sensei.sops.yaml
## sops --decrypt ./kubernetes/apps/default/sensei/app/sensei.sops.yaml | kubectl apply -f -
data:
    .dockerconfigjson: ENC[AES256_GCM,data:VWQxubGppbSMnya7WJVx58CLHXK3QzErqtRV9AZ3QZxyxSZDmVvu0uNy2zH9zIPBy5+/WT2ZEAnWm6y1BK/Mt7Tc+0AB6fL93uIF5uIKpMWiDFJBT6O/6FleqO5I9OhaEDDeejeAsrFe4FrJo2nWOYRUvzK3I7z5+GMoPgvBfPmKc9DkG85DQ2cT7cHimSVpGCe2tTL/P+K5D9ymGIm5Wq98wIAMPPjEiUbsRWUI8aD21xpCPh3jCu9kUcL+LSJK74+U/bKX1sVsRTIenu/4SfIm0Az0lo9fbPihcUDZUPruwpigUqm3X78e0UCcTIozZWGZVBP/lP3Mo1/3Rmp9O23TtYTOHDtf83DsLOXXyGaAxBg+5otf/sccGRzx/wJg,iv:SLr3nWvE7q5HZeL/ZKoOlRamhivllZRAHPoogltiI0g=,tag:tg1UWeMiUmvRuNr2R9mRwQ==,type:str]
sops:
    age:
        - recipient: age1q6l62kwaly44pl9vwedqvxtxv0fsndtq53s6kzclsccslne7cpfs2352vr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5YkQxdFBIVWh0eWtaeVZ6
            ZGtVUE85WFdCNktSK2pmUmVlZW95V1NpTFhJCklrWXFsbHdSVVpVcEpOTUdlR0I3
            MDdYcUdlT044VjhmMFFpL2lQR0ZUbTQKLS0tIFhtdTRsdFozK3VqajdiZDNrcGZF
            OUpsalBnM01VaFM5blQxZXNhblV3WUUKoHDxccQBoUt15TGbs8JLMVgdZFVAvRAD
            SYFJNXWQgHbZIyOXSr3uDWvmP4BG9zzLOb5t+EosSZu3Iup6C2vzPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-03T01:58:33Z"
    mac: ENC[AES256_GCM,data:0LI9/rwGD4mk0c21vCFQStpzfo4q6pz5eTe1L2FfvBorSvRaljQMpGhzZmgl1T/z8jGw1yp1ehaOy2d0FQtZZjG7O1S/B9QsmEn8aO+qUsjCqz1PLFtVYVpCe2txN0J7fe9u+jvqt6LcZICG373lDf8pUPiRQWZCPcp05Et91AM=,iv:80Sn168lgXnieHIjTr71Tm3zmOktXtYBiPGmeAEN94Q=,tag:zb74hakL7GSjJCzzHoAsLw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
