---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app influxdb2
spec:
  interval: 30m
  chart:
    spec:
      chart: influxdb2
      version: 2.1.2
      sourceRef:
        kind: HelmRepository
        name: influxdata
        namespace: flux-system

  values:
    image:
      repository: influxdb
      tag: 2.7.5-alpine

    securityContext:
      fsGroupChangePolicy: "OnRootMismatch"

    pdb:
      create: false

    adminUser:
      organization: "default"
      user: "admin"
      bucket: "brad"
      existingSecret: "influxdb-secrets"


    persistence:
      enabled: true
      #useExisting: true
      existingClaim: pvc-influxdb2
      name: pvc-influxdb2

    service:
      type: LoadBalancer
      annotations:
        io.cilium/lb-ipam-ips: 192.168.3.9      

    ingress:
      enabled: true
      className: external
      annotations:
        external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
      hostname: "influxdb2.${SECRET_DOMAIN}"
      tls: true