---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-influxdb2
  namespace: database
spec:
  storageClassName: "network-storage"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.2
    path: "/volume1/network-storage/influxdb2"
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-influxdb2
  namespace: database
spec:
  accessModes:
    - ReadWriteMany
  volumeName: pv-influxdb2
  storageClassName: "network-storage"
  resources:
    requests:
      storage: 1Gi
