---
# yaml-language-server: $schema=https://raw.githubusercontent.com/kashalls/kromgo/main/config.schema.json
badge:
  font: Verdana.ttf
  size: 12

metrics:
  - name: talos_version
    title: "Talos Version"
    query: node_os_info{ name="Talos"}
    label: version_id

  - name: kubernetes_version
    title: "Kubernetes Version"
    query: kubernetes_build_info{ service="kubernetes"}
    label: git_version

  - name: cluster_cpu_core_total
    title: "Cluster CPUs"
    query: sum(machine_cpu_cores)
    suffix: ""
  
  - name: cluster_cpu_usage
    title: "CPU Usage"
    query: round(cluster:node_cpu:ratio_rate5m * 100, 0.1)
    suffix: "%"
    colors:
      - { color: "green", min: 0, max: 35 }
      - { color: "orange", min: 36, max: 75 }
      - { color: "red", min: 76, max: 1000 }

  - name: cluster_node_count
    title: "Nodes"
    query: count(count by (node) (kube_node_status_condition{ condition="Ready"}))
    colors:
      - { color: "green", min: 5, max: 5 }
      - { color: "orange", min: 4, max: 4 }
      - { color: "red", min: 0, max: 3 }

  - name: cluster_memory_total
    title: "Cluster Memory"
    query: round(sum(node_memory_MemTotal_bytes) / 2 ^ 30)
    suffix: " GB"      

  - name: cluster_memory_usage
    query: round(sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / sum(node_memory_MemTotal_bytes) * 100, 0.1)
    title: Memory
    suffix: "%"
    colors:
      - {color: green, min: 0, max: 35}
      - {color: orange, min: 36, max: 75}
      - {color: red, min: 76, max: 9999}


  - name: cluster_network_transmit_usage
    title: "Network Tx"
    query: round(avg(instance:node_network_transmit_bytes_excluding_lo:rate5m / 1024 / 1024), 0.1)
    suffix: "MB/s"
    colors:
      - { color: "green", min: 0, max: 50 }
      - { color: "orange", min: 51, max: 75 }
      - { color: "red", min: 76, max: 1000 }

  - name: cluster_network_receive_usage
    title: "Network Rx"
    query: round(avg(instance:node_network_receive_bytes_excluding_lo:rate5m / 1024 / 1024), 0.1)
    suffix: "MB/s"
    colors:
      - { color: "green", min: 0, max: 50 }
      - { color: "orange", min: 51, max: 75 }
      - { color: "red", min: 76, max: 1000 }

  - name: cluster_pod_count
    query: sum(kube_pod_status_phase{phase="Running"})
    colors:
      - { color: "green", min: 0, max: 9999 }
    title: Pods    

  - name: cluster_age_days
    title: "Cluster Age"
    query: round((time() - min(kube_node_created) ) / 86400)
    suffix: " days"
    colors:
      - { color: "green", min: 0, max: 99999 }

  - name: cluster_uptime_days
    title: "Uptime"
    query: round(avg((node_time_seconds - node_boot_time_seconds) / 3600 / 24), 0.1)
    suffix: " days"
    colors:
      - { color: "green", min: 0, max: 99999 }

  - name: prometheus_active_alerts
    query: count(ALERTS{alertstate="firing"})
    colors:
      - { color: "green", min: 0, max: 1 }
      - { color: "orange", min: 2, max: 4 }
      - { color: "red", min: 5, max: 9999 }