apiVersion: batch/v1
kind: CronJob
metadata:
  name: sensei-stage-daily-refresh
spec:
  schedule: "0 1 * * *"  # 1AM every day
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: stage-daily-user-refresh
            image: ghcr.io/clarknova99/project-sensei/backend
            tag: stage-latest
            command: ["/bin/sh", "-c", "python3 /app/daily_refresh.py"]
          restartPolicy: OnFailure
          imagePullPolicy: Always
          imagePullSecrets:
          - name: sensei-secret