apiVersion: v1
kind: Secret
metadata:
    name: sensei-secret
    namespace: sensei
type: kubernetes.io/dockerconfigjson
## echo -n "username:ghp_YOUR_NEW_TOKEN_HERE" | base64
## sops --encrypt --in-place ./kubernetes/apps/default/sensei/app/sensei.sops.yaml
## sops --decrypt ./kubernetes/apps/default/sensei/app/sensei.sops.yaml | kubectl apply -f -
data:
    .dockerconfigjson: ENC[AES256_GCM,data:Bjlm7JfPXlYhfX5X//esNF+jyEhJN/prk1mVR1lUnro/qSwoRhUMA6IVOxjoDBjzK5LCpotQLKyU5ONEBsYm0RUJvCQqFYxuTj5Mzu+28q5JVs78g/bAFJuZhNCJ7NdNwbIi7UEUTJXCRMxwTaq7SXXI2N6SwM7EnnvCT0nheJmOHS2evtmi2W2HWvG/R8IRemiIvAevhc+USY33fQvIxJrwlFua8fp99JJfk+/OhAWJgbcWlk4eCAbAk9gtBiExZzgUICn2e4QruvRchMJjCMkET5rU99TTCM9/F8cmEZUWJv04qSL74PRkIVq4z6R3vtqrHCZHlWeaso6T+qMoSyr7dse6UmGj+WG/L3uFFBF3pt4Vt9hQP+3pLi0R+Kro9K7zjA==,iv:HlUKGQrJrQDu5ku+wr4r9NxQYaB0ojX0oc6MIIwZVNY=,tag:00bL2s5x98RQcjMtnMfNlQ==,type:str]
sops:
    age:
        - recipient: age1q6l62kwaly44pl9vwedqvxtxv0fsndtq53s6kzclsccslne7cpfs2352vr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5YkQxdFBIVWh0eWtaeVZ6
            ZGtVUE85WFdCNktSK2pmUmVlZW95V1NpTFhJCklrWXFsbHdSVVpVcEpOTUdlR0I3
            MDdYcUdlT044VjhmMFFpL2lQR0ZUbTQKLS0tIFhtdTRsdFozK3VqajdiZDNrcGZF
            OUpsalBnM01VaFM5blQxZXNhblV3WUUKoHDxccQBoUt15TGbs8JLMVgdZFVAvRAD
            SYFJNXWQgHbZIyOXSr3uDWvmP4BG9zzLOb5t+EosSZu3Iup6C2vzPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-02T23:33:58Z"
    mac: ENC[AES256_GCM,data:k8+79sOcaXarqU4jr+xFNWsA4TEFWJmjwmlY2TmiTJ7OtJGORlBK7Xq5mxMZSRNt0pK4lC6YUj97pFNUCvkjtfpou6c3uj8zk0qDN0SA7GpMGvzWfcwLgKi1USyrMOj11kRKGd0NxN8T7WtvQS9Pr+rsdRDPXQpiJ0se4HrU63c=,iv:eoQBlNvZLaWnqIw3Sld0mjY+rigEP1r32d/VBQ3jAaU=,tag:EaEdvtr0eqqzzc2e/vHakQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
