apiVersion: v1
kind: Secret
metadata:
    name: sensei-secret
    namespace: sensei
type: kubernetes.io/dockerconfigjson
## sops --encrypt --in-place ./kubernetes/apps/default/sensei/app/sensei.sops.yaml
## sops --decrypt ./kubernetes/apps/default/sensei/app/sensei.sops.yaml | kubectl apply -f -
data:
    .dockerconfigjson: ENC[AES256_GCM,data:wS09oJ+R+tfXpPp0n7GxG1V1F+vDF5WkE589rHBZdnm7oNtNDDBBw+/hlmSXScZAkqqyLvOpdI9+NMAKkch5G7g3QKdR8RpEC+O770a0p8dpVrxqbqfIfRmil0/rtdFbSAdYtfUdtgcQCNYhhw6DB1u0VjEQ8t7dH4vsmkaHWTR0KNzLPRt67FbTGLDJPtlM7taEohe0LQu4cTJdejcx1+dckNEY1AT4RR4hdnOV79CTF7NOGSsbg3dD98RlJDXEz6KJys1ox4+FPTp5/4YO4V6IocSoaCtamq2u/aIaxQvRAE0H9Ggi6ra5jA82fgZuw1PrEHl9zDO3nwmGf8uHcIh83lb0PrVClkU+epqU6auIARjtkVIcV0++pRZ/UHzL,iv:pkpBIBjGZxdaZRD7w3mUf0/hGXtULjKrjvSosv39HLo=,tag:y4vaSqwFSEkkpFXcCu38Pw==,type:str]
sops:
    age:
        - recipient: age1q6l62kwaly44pl9vwedqvxtxv0fsndtq53s6kzclsccslne7cpfs2352vr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5YkQxdFBIVWh0eWtaeVZ6
            ZGtVUE85WFdCNktSK2pmUmVlZW95V1NpTFhJCklrWXFsbHdSVVpVcEpOTUdlR0I3
            MDdYcUdlT044VjhmMFFpL2lQR0ZUbTQKLS0tIFhtdTRsdFozK3VqajdiZDNrcGZF
            OUpsalBnM01VaFM5blQxZXNhblV3WUUKoHDxccQBoUt15TGbs8JLMVgdZFVAvRAD
            SYFJNXWQgHbZIyOXSr3uDWvmP4BG9zzLOb5t+EosSZu3Iup6C2vzPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-02T23:42:06Z"
    mac: ENC[AES256_GCM,data:PKmcvCK997NXfcF+QLE+YwEpH//0PdXZ1vFXgmRHBtifVtEaylo2XCU7+deVu50TK3/Dw7nlhaK/AjmH8IFDRI75lBSarEW0xH4DQHfU6fcWjaITXs2UhUqqrErc0d1do/pKARkX25XIy1hwWO+NF+0khT4w2IAA0r4hjlTHkYI=,iv:BUPUJcveWq+5eSeFzi+xnG13cH27AmeawMFsprUBPS8=,tag:sSG46V4OOTswPHKU33UicA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
