apiVersion: v1
kind: Secret
metadata:
    name: sensei-secret
    namespace: sensei
type: kubernetes.io/dockerconfigjson
## echo -n "username:ghp_YOUR_NEW_TOKEN_HERE" | base64
## sops --encrypt --in-place ./kubernetes/apps/default/sensei/app/sensei.sops.yaml
## sops --decrypt ./kubernetes/apps/default/sensei/app/sensei.sops.yaml | kubectl apply -f -
data:
    .dockerconfigjson: ENC[AES256_GCM,data:iNpI2VzCBzT12akEccE2XuYjsD/+PJPEEo0JMbO3+mEVSty3XEvnxEOO8Fo+TWZlS9UJq3lRQ0OBuFryeqgT/KFXpK/lpmshoWG9OjH+MU5tUkPvzGJ5lGNhd4dVa0RmLCPpNnAaMxaDQkZWmx2Z/PosIHW1mH7qXkHdEimEjdOh4tnr4xE7oboByXf9hjtXVzAIkEi5jOtqCB5wAGSPdUKXn5DmSetdm0uxPiv3z51PY7301JdZnA9CDlK/LhpTHNXjware322qSMioSZJR0D9MBtMBUL7d2wjLQ3wX/nxKtV3R/pViIYJjp03dBviBfUhqGKZKRksWdiPZqc0Ik2cRtS+wcMh48nR2UdJwUXyIdq4Y2/O5qhk9fRHUIQjwQ8+ucQ==,iv:GjP6IlwEbHq+u69D5yhiiowq3Ylpjn1cevboU5T/X/Y=,tag:uOHiBg04QWbpHRug5i/raQ==,type:str]
sops:
    age:
        - recipient: age1q6l62kwaly44pl9vwedqvxtxv0fsndtq53s6kzclsccslne7cpfs2352vr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5YkQxdFBIVWh0eWtaeVZ6
            ZGtVUE85WFdCNktSK2pmUmVlZW95V1NpTFhJCklrWXFsbHdSVVpVcEpOTUdlR0I3
            MDdYcUdlT044VjhmMFFpL2lQR0ZUbTQKLS0tIFhtdTRsdFozK3VqajdiZDNrcGZF
            OUpsalBnM01VaFM5blQxZXNhblV3WUUKoHDxccQBoUt15TGbs8JLMVgdZFVAvRAD
            SYFJNXWQgHbZIyOXSr3uDWvmP4BG9zzLOb5t+EosSZu3Iup6C2vzPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-02T23:16:53Z"
    mac: ENC[AES256_GCM,data:a31hhjQR4XjGNPUNSCTkuxWejgxcho7QNSQ3KpG6c2yzpHbQEHt8xYW4dCWUo/IQU6LCCx+42ge5g/RrEsrJ/gqWrgMHIpxye88rlBdaBIHoihCzbOSY0Bmf1ILlI3DAC1Gl8mTjWjqPjngk7sFsaG+x839Rj5EcU1h510b+V1M=,iv:ZOxuLcmD9Y3/mwx13d+T7FABHhjQZKKV5u34Te8Q8Yw=,tag:+g3V7m9uWCl7o40juXBZMw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
