apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-password-secret
## sops --encrypt --in-place ./kubernetes/apps/observability/grafana/app/grafana.sops.yaml
## sops --decrypt ./kubernetes/apps/observability/grafana/app/grafana.sops.yaml | kubectl apply -f -
stringData:
    admin-user: ENC[AES256_GCM,data:R0z+cARCbFi7KaJdbA==,iv:317Ezi21n806Wz3baoSDgDB+SwK2ynnuCJ4O4dTCvQ4=,tag:F80XGnmxIGRdDoGHfy7sDA==,type:str]
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:wO57EOoSBiG6,iv:ARoN3ejf40195lkbiDPOT5iqUZwpJHyC65kyaPeWPmw=,tag:fvRsgyvjEexCsfS1ODwXxg==,type:str]
sops:
    age:
        - recipient: age1q6l62kwaly44pl9vwedqvxtxv0fsndtq53s6kzclsccslne7cpfs2352vr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2QUpIaWNPaFZWczhHTG9D
            T2VPbHRwUEdQY1BzQTRDVUZHSzM5UENuYTA0CncrSnZyZm9KdGdoZ01MUDJ5bndZ
            WGtwcmlLWnJ3anNSN3RqajQ0NkxRR3MKLS0tIDZJZkJGdVZMajVicVlrQnRIUkNB
            TC84RXRBdzZJQUJFbTF0a3cxeVFvSzAKrIEI7DJKXVaBBG9CkVbRdO4UTlSwroAk
            jiCs6A69UVabrtJvDs4x3zmIYDE0Fnro02FPaLL293aU2+P5HYdnnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T19:40:44Z"
    mac: ENC[AES256_GCM,data:VgZCj63DRR/JImbsN2bNdDSGoq06X0FZXAX8r3A66o/2IxxS5tDey8iysKZzGahKmvcKo0IrDEOQyFpT56lbgajS7dmyzEYwar9igQ76IBoMFV7ie+WX+06jo0M+sujIVxQ6Z8nfMFYPuaglCXtkNEK8V/HvxpBdkBV7zPeME+s=,iv:M14ZUdZqcCTlppDhGLd7c+lFzZUQFDCqOV1IAtvZi8o=,tag:irzlcDEe0lNO7WJfBov0Sg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
