apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secrets
## sops --encrypt --in-place ./kubernetes/apps/observability/grafana/app/grafana.sops.yaml
## sops --decrypt ./kubernetes/apps/observability/grafana/app/grafana.sops.yaml | kubectl apply -f -    
stringData:
    admin-user: ENC[AES256_GCM,data:W9lz8jpWig==,iv:+9VrbPAsaco7DC9lJNxcvKcthjcPxp2lR5Nw5SP0cYw=,tag:9wfSzz5immQRCAw8bCfyxg==,type:str]
    admin-password: ENC[AES256_GCM,data:LYsWtQ6VhMJ2,iv:EeIRi50DoB3Upj4Y4HnyXHrwzdOp/eIX/Ylpy7TQmt4=,tag:vzZQZ/jc8Vze8pp5ZKta6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q6l62kwaly44pl9vwedqvxtxv0fsndtq53s6kzclsccslne7cpfs2352vr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2QUpIaWNPaFZWczhHTG9D
            T2VPbHRwUEdQY1BzQTRDVUZHSzM5UENuYTA0CncrSnZyZm9KdGdoZ01MUDJ5bndZ
            WGtwcmlLWnJ3anNSN3RqajQ0NkxRR3MKLS0tIDZJZkJGdVZMajVicVlrQnRIUkNB
            TC84RXRBdzZJQUJFbTF0a3cxeVFvSzAKrIEI7DJKXVaBBG9CkVbRdO4UTlSwroAk
            jiCs6A69UVabrtJvDs4x3zmIYDE0Fnro02FPaLL293aU2+P5HYdnnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-21T16:38:53Z"
    mac: ENC[AES256_GCM,data:Md2tqmR1Dqu6Xe2EcqZKcun3tmlkPd28aeT8GojEbq/Tn9dj2qiofqXpFrjxpIyBj+Fsp1PCeqD7l/MsUvZ5yyg7XnfhPvrRm+xrT4UgBKuPhd4FNZSBnhKFA08vntBEr+Q+YkH0C4X+YXlhWiUj0EyF9P6lJYMH7RuPaBXHaVI=,iv:eBkad7evx7zm2T6ccpsqArKvDg8ag798vKxz8km7HvE=,tag:WreA2OCA977JX8bDWS+WCg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
