apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secrets
## sops --encrypt --in-place ./kubernetes/apps/observability/grafana/app/grafana.sops.yaml
## sops --decrypt ./kubernetes/apps/observability/grafana/app/grafana.sops.yaml | kubectl apply -f -    
stringData:
    admin-user: ENC[AES256_GCM,data:R0z+cARCbFi7KaJdbA==,iv:317Ezi21n806Wz3baoSDgDB+SwK2ynnuCJ4O4dTCvQ4=,tag:F80XGnmxIGRdDoGHfy7sDA==,type:str]
    admin-password: ENC[AES256_GCM,data:LYsWtQ6VhMJ2,iv:EeIRi50DoB3Upj4Y4HnyXHrwzdOp/eIX/Ylpy7TQmt4=,tag:vzZQZ/jc8Vze8pp5ZKta6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q6l62kwaly44pl9vwedqvxtxv0fsndtq53s6kzclsccslne7cpfs2352vr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2QUpIaWNPaFZWczhHTG9D
            T2VPbHRwUEdQY1BzQTRDVUZHSzM5UENuYTA0CncrSnZyZm9KdGdoZ01MUDJ5bndZ
            WGtwcmlLWnJ3anNSN3RqajQ0NkxRR3MKLS0tIDZJZkJGdVZMajVicVlrQnRIUkNB
            TC84RXRBdzZJQUJFbTF0a3cxeVFvSzAKrIEI7DJKXVaBBG9CkVbRdO4UTlSwroAk
            jiCs6A69UVabrtJvDs4x3zmIYDE0Fnro02FPaLL293aU2+P5HYdnnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-27T20:55:55Z"
    mac: ENC[AES256_GCM,data:yx8bX54rSbUWUES5zyWOSZOsEYl3BWKn1UuBg8FoL2oUklbXeRsKzJnmNz/x3xiEFFGLvv8ypzDyr2heTh3p1TSj0aGkCKKvAGNW7P1rcHqI7opptDuQa+dUjfjUH2DwnMs2JuDEzEwo2PADTenvYFwWyVnlEjJ4fH+GkwP2zL8=,iv:540cI/JBmegsc+8PurWJxOW0ucX8KhiQFpA/0UvjUFQ=,tag:EKd2Cnnyzy2nGWMEDJVesA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
