apiVersion: v1
kind: Secret
metadata:
    name: sonarr-secrets
## sops --encrypt --in-place ./kubernetes/apps/media/sonarr/app/sonarr.sops.yaml
stringData:
    #ENC[AES256_GCM,data:5dODVQ==,iv:Wyzt+MycdVyqNCocnMZSgRCd2nFahGh7NzB70qpOh90=,tag:SWHzfjbDSH98AATGPVkOUQ==,type:comment]
    SONARR__API_KEY: ENC[AES256_GCM,data:NkZuhr0yJmtN3gW+Fdh4oHN1Bc4EW+LXlYYvOTB1eqo=,iv:/hhk15vHA8+kodKSjCd9T5ftCakAIIzZtqUhfd7K6BM=,tag:52oOSYW5L6vZnBAe72AtiQ==,type:str]
    SONARR__POSTGRES_HOST: ENC[AES256_GCM,data:1vqo0J9bdDuK88vFq/ziU7v3T1W8v/QaWtkoggNv2SCo9XZFIkr2xA==,iv:gErmzfeT5+pQcF+8kcGFxnjA+6m3vqcE2mLEQBw6F9s=,tag:F9/JAW0xQeM8Sgx+HWsYbw==,type:str]
    SONARR__POSTGRES_PORT: ENC[AES256_GCM,data:uCL60g==,iv:KA/D5KhStTQGhRsLTx47pQrAhF2j7wGGCBu12XG5oFs=,tag:DmGpnOZEdSoYb8fDjlXalA==,type:str]
    SONARR__POSTGRES_USER: ENC[AES256_GCM,data:VHsKmW90hwQ=,iv:2q0zzQcSkHOXMXaz173vYwAW9ENYdZR3YhgRSMnr10k=,tag:uLkuUMQP9qsVW8wHuoA+TA==,type:str]
    SONARR__POSTGRES_PASSWORD: ENC[AES256_GCM,data:bR5R556zq65l,iv:6uFvXYycnMK2/Uo8vAhJw9bI25Y259T9pHHx85aOXcs=,tag:puI0Nwf8WYE+bhjzpgNvpA==,type:str]
    SONARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:pPBtodKqORiPnsg=,iv:/o17MB4vqOXp7rDKEjSjxGOph/8C8jAS2P5fyeHnkVg=,tag:OaYC77xliMIRdF/cRSWCBg==,type:str]
    #ENC[AES256_GCM,data:S1r5+lu3YYafgKXwo0c=,iv:vdQoH5wJ+gB2iLDyuwkPiI/4OuPVujLd8S7Ryi/0Ctg=,tag:/kwHZBuIML5GLOr8//+BSQ==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:ebR8XOrO+VBL9ls=,iv:a/86Wplcpo/0BLzjk+/dxxIp9oWFZbhzOl9oorYRJVk=,tag:AbQavADY7gs71BtWOXESBw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:wDYU9mFblIBbPNgJbJEBtfxQUxXsSxIXcNFafV6Z1KNTQNhmnVk6yw==,iv:lgOSPwWGTAs6RbJDlYjc2jVccxfl0UgO5CDn957ZAxI=,tag:2ukpA1wxjejTPYxsajwlZQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:gkpc1PmqBVo=,iv:4pfgsA8aSElKxcq1IvZ7nkbOpoKniPsPlK9MXICeLSg=,tag:GMf+DskU7lrQ2rA2SblwKA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:97KVO4ANI2zD,iv:Ifd2D+71n12p23u6mSWLXP2Nb1K8p6tIKVTGjcmBQmg=,tag:XvO0VOC/9j2u7UuwplZ/IQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:TYgEGNuMbn2I,iv:UVgBS6oTTffIuzneprcfClZbpxk/kVbS29z147XF6rQ=,tag:DjU1T96WuvwmK9v+/cLg1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q6l62kwaly44pl9vwedqvxtxv0fsndtq53s6kzclsccslne7cpfs2352vr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlT3R2bTlHNm0rN1gwS0k2
            VlhKNjhIR09uV1l1bnBnRVFZTzVqYXB4K0dNCmJvWFFwZklyT0dKeFZkZHMyd0pZ
            cVJabnQyc3F3dmZFVm8rK3pPNU8wcXMKLS0tIHR6eW83alkwdU1qRmNxQ09pSmQ2
            Nnd2dldlVXQwN3JscVlReVNPc0RheTQKiOeLp9Z8eqGMb7Z2GxQBFzDta1fPqdmL
            iECzYnjD6+KsIaDtgHZCKk7dfgulwEv3RKRaTKO5/CoiQUqpe+C6aQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-13T03:51:51Z"
    mac: ENC[AES256_GCM,data:wVDzy6DnOQlYtgxeSLtIErep3Iv2cf5XfK+fRh/gXndD+Ns/t0kpcwdXhQ9oh2NZa7ElMMrEj4dCLzUdyzJX4VEp9+Lg/HXpzaRLE4ufx1QTMsCLIyPskbgRLbcSQh2M4rzCKydF6qIJBjlyj63737c1qU33dYmvISe7l2SwhyQ=,iv:Tovm1TkTPZ/agNkdZsIeJwmiFghaLNiG2hNa2PNYGVI=,tag:3HzwUMcLEz50YVNQ1Agz2A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
