apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-nfs-pv
spec:
  capacity:
    storage: 10Ti  # Adjust based on your requirements
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""  
  nfs:
    path: /volume1/network-storage/cluster/minio
    server: 192.168.1.3
  mountOptions:
    - nfsvers=4
    - hard
    - nolock

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  volumeName: minio-nfs-pv
  storageClassName: "" 