apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:7CJobza+by7q6dGDmIFHWjIN3ClOD70dDDe6bYIZ1g7x5hTKLUCyqw==,iv:5Q1vfixNmKIh3rXkRh2LW2bUQIK+hRxZ9OBNjec4iXA=,tag:X4aK09QUGr1CpydgusVINQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q6l62kwaly44pl9vwedqvxtxv0fsndtq53s6kzclsccslne7cpfs2352vr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlRGVUdk1ieW5PRThSRjdj
            aVo4aVBmZkxjMEp6SGF3citUSStFRDNycHkwCjV5d3BOVmMyWjV4bFA2eE9Odi9T
            enpuSmVFLzA0NjZqbTQ4Q2ZybW5uYWsKLS0tIDE3cHF6YUN6aTNHbjR1SkY0T2dl
            WTFVcGNwN3NobVFIc3RIN1RVWW1KUjAKSkrtrQ68mpfUuGCWtOP36na9/K3dprnq
            jXpkurVer6XfoBykrayCNClpRdPOqtlE7gJb7gzbmVhZ1iWISTO13Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-19T16:17:45Z"
    mac: ENC[AES256_GCM,data:e/ZL47WLq1JSNQoQc7Ghwi40eSeG/ZVBiBpS2wp+NMMZ5rVvAKKJCrb1gcZvotl+XwLOgwt4Ci6VqTZmeK7U76Uyz8neldxVvGoo4YHbD/6+zO86L3jVq0x6+hhv4+acNBZuPG3MSBFCUqNrE5DdMUmrDCr6T9Pai0jGFxnZvgo=,iv:GANbt3YPuh+DDcnAPSfnOiLOdzWuKTKop6SEylX0WR4=,tag:u3ESZmKFWD37MSm7PpEfCQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
