apiVersion: v1
kind: Secret
metadata:
    name: prefect-db-secrets
## sops --encrypt --in-place ./kubernetes/apps/default/prefect/server/prefectdb.sops.yaml
## sops --decrypt ./kubernetes/apps/default/prefect/server/prefectdb.sops.yaml | kubectl apply -f -
stringData:
    connection-string: ENC[AES256_GCM,data:KtPW9qmrjRNQge1R6vMvCPYSBJSbklqVunCqHTQ14QK/47WvepTh1bvE0oNhB9fYHI6q2WfhvGpAdikLviApNOE4yfA3QVDmbgfOc9mJGQauuyAW0oDFqw==,iv:vZCR0uczU7h+WuhfWlhPZIpzoouVQ31mQzSpSIYOF3g=,tag:pJqAyP/j9AOY9AqQdo3iOw==,type:str]
    host: ENC[AES256_GCM,data:5nv7uH8GeCp8IhnloC52xRwCRp0Z1Y6KjsePepgzPRL5XbEHU7+87Q==,iv:MzD20adGUmm9MZWXnLk6EQIYxIRVM+cwB4Hr/4pq8go=,tag:kfMDyezB+B0aG8FVI7o8dA==,type:str]
    username: ENC[AES256_GCM,data:CALXMZ2NBns=,iv:SLjsdj/GKIqRzRkYiKvqPF5KcXfC44aqh71qEOvm/iY=,tag:8jFeImoEkpDhaKVgmbaNzg==,type:str]
    password: ENC[AES256_GCM,data:BYbtIyj+Tr8Y,iv:dN6XmdFP+PYMmGj0U+/4jRJnBYWit4nljSruCqE/U4s=,tag:emaDekV2xT/86QTwvFr2dQ==,type:str]
    database: ENC[AES256_GCM,data:ZSRCnbmOUA==,iv:OactaF/aRZO7twWj3PsjA4JdQe2FQG7jZwALSrPBKLs=,tag:qKdimQrLPtQsxgSpStAuGA==,type:str]
    port: ENC[AES256_GCM,data:xOibOQ==,iv:I8PvV5xyTvBdQd4voCy1ckTIeMRsccb5/xgQpfA+Wuw=,tag:fmnnBbqKUSHhRLmfcT4svQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q6l62kwaly44pl9vwedqvxtxv0fsndtq53s6kzclsccslne7cpfs2352vr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZEhUSjQyVi9IdXB6VUpQ
            K3pVb1hZQk02b2NKNmJwbm9EaE51RG5pcFFNCmJsM29BdVlyaFVma25pbENMamhQ
            MEpaYXJSQ3BpRHQ3MVNWZ0NleXduT1EKLS0tIC9DVE1vMFJudXJHTmI4NmZUSXd2
            WGR4RzN3cjJBeStDZHlWcTBkdEE1Ym8K0FnNxK7kOkPf+CT01qvUI/CSk9QUM1hi
            Z85rdKcwCWNXFx/NnSOekPsd1CEXprXnaGib2tifsQvt9ZJHSKx0jQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-28T18:47:59Z"
    mac: ENC[AES256_GCM,data:w+OmbJcC481CkU940dDRrlKlVRJRbTIeWh0HZDyaq5A/i1mMbrEm0HYHMpS4kkFCoRhFDYerU0cMHqDLbf8cXvLFhNkDQS7TfOxX++O1L0gcu99/vQCBhDxmRdcBF4m4bxB3RcnfSgMibz+QugEBsj8mbZGXxw6AxBapwBWN3PY=,iv:0DmW2VvvNtH6gND2WtXoKh1biQ4b9m9HvBBAHxZzL4A=,tag:On8Ry7bsB2xJ0ed+/DCDiw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
