apiVersion: v1
kind: Secret
metadata:
    name: gatus-secrets
    namespace: observability
## sops --encrypt --in-place ./kubernetes/apps/observability/gatus/app/gatus.sops.yaml
## sops --decrypt ./kubernetes/apps/observability/gatus/app/gatus.sops.yaml | kubectl apply -f -
stringData:
    #ENC[AES256_GCM,data:vJ2Mw1KE70i/N7vC6lY=,iv:xizuDyqJTZlSP4QMntQDG0ZTrPakZqcjg37Qd2wiey4=,tag:yRNKQ/RAlmrmgaf9dYC63Q==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:bgE1YAo=,iv:Qowke07g1R7bYqRTo4ggqlMEHc64KLujFbvVb4Stbts=,tag:BqJ7IgrF7XwZH6TOikMaDQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:8NxbLmWy403uHqArQIgdmtNFmJGZmiiVqwxW97Vm76yW6MGJ5/+lgQ==,iv:h6puBJdUEpd1VYDy6W7YJIRTuFfPVS7x+VgZy680fbc=,tag:al77Ah193mmJDdWNK9Ss/Q==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:ijvuC5VS0BA=,iv:I6Tb3deysChsc+/GLMPgUbC0VphBNk5XX/q7Vt4NkzU=,tag:tctQ2jk6PwusMupjCKWHVQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:O+HalBcNydTU,iv:LvwoH79Mcg3pG4d+ER57r/BsM+vVdJqMYMRAkOI5qvM=,tag:gD9nYw+WI3RVZD/E4WHV/w==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:YP8oGMpF38ei,iv:pLkMKiqanKzOdq3zcxf4jdkNNpmz13BoseMBuL6k6jU=,tag:U7NtW1W8iJttGLV/YGZ0ow==,type:str]
sops:
    age:
        - recipient: age1q6l62kwaly44pl9vwedqvxtxv0fsndtq53s6kzclsccslne7cpfs2352vr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuS3dPdklIcjNoY3puQ0JH
            d1dqWHVGK2JHU1AyeWR1aytjZU9rUDVhTW0wCmk2Mi9XRkNMbk81bThvSDczNFdX
            TVhqU3JRNU92S3NZbnd3WUdWSmJsKzAKLS0tIEdsamtYVVBZYWoxQkxlRWFqS3hT
            SVVkYkl2QXptYk1BMEl2ZFc3cmJENDAKU+99LAPvoEpV5eGZYT14C30n68Zj7xNt
            HQUbvSVBWn3kqnU4M1aeDIE9jQDqR+g1KbFD3L/8VJ5jgzzdKMRXLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T18:13:27Z"
    mac: ENC[AES256_GCM,data:2YayQAwkd9K7eZi9VqhDW+RnfisZTVt5swgwm20igKP2ggiNTV3aK3AYcDz7ChKfaXHIeIeo5bJ9H5flaNh13HIRlM/thPJIzHF0DdEL5adpFnyvcXNGg3zPHHW4ZNLjZ937g4VA4njMUNmaNOFfaoDOAsIoWdnBzYyEAgWi0Do=,iv:fSXwGOP4u00Yrod4v2JpbRS1+EPar4aSL0ddxYif8IU=,tag:GJ1lgghKOoYmbwOCtFBBBw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
