model_list:
  - model_name: llama-3.3-70b-versatile
    litellm_params:
      model: groq/llama-3.3-70b-versatile
      api_key: ${GROQ_API_KEY_LLM}
  - model_name: groq-llama-3.1-8b-instant
    litellm_params:
      model: groq/llama-3.1-8b-instant
      api_key: ${GROQ_API_KEY_LLM}
  - model_name: groq-deepseek-r1-distill-llama-70b
    litellm_params:
      model: groq/deepseek-r1-distill-llama-70b
      api_key: ${GROQ_API_KEY_LLM}
  - model_name: groq-llama-4-scout-17b-16e-instruct
    litellm_params:
      model: groq/meta-llama/llama-4-scout-17b-16e-instruct
      api_key: ${GROQ_API_KEY_LLM}
  - model_name: groq-llama-guard-4-12b
    litellm_params:
      model: groq/meta-llama/llama-guard-4-12b
      api_key: ${GROQ_API_KEY_LLM}
  - model_name: gpt-4o-mini
    litellm_params:
      model: openai/gpt-4o-mini
      api_key: ${SECRET_SENSEI_OPENAI_KEY}
  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o
      api_key: ${SECRET_SENSEI_OPENAI_KEY}
  - model_name: gpt-3.5-ft
    litellm_params:
      model: openai/ft:gpt-3.5-turbo-0125:personal:sensei-fine-tuned-v1:B0PBp7HZ
      api_key: ${SECRET_FT_SENSEI_OPENAI_KEY}
  - model_name: openrouter-minimax-minimax-m2.7
    litellm_params:
      model: openrouter/minimax/minimax-m2.7
      api_key: ${SECRET_SENSEI_OPENROUTER_KEY}
  - model_name: openrouter-nvidia-nemotron-3-super-120b-a12b-free
    litellm_params:
      model: openrouter/nvidia/nemotron-3-super-120b-a12b:free
      api_key: ${SECRET_SENSEI_OPENROUTER_KEY}
  - model_name: openrouter-elephant-alpha
    litellm_params:
      model: openrouter/elephant-alpha
      api_key: ${SECRET_SENSEI_OPENROUTER_KEY}
  - model_name: openrouter-openai-gpt-oss-120b
    litellm_params:
      model: openrouter/openai/gpt-oss-120b
      api_key: ${SECRET_SENSEI_OPENROUTER_KEY}
  - model_name: openrouter-openai-gpt-oss-20b
    litellm_params:
      model: openrouter/openai/gpt-oss-20b
      api_key: ${SECRET_SENSEI_OPENROUTER_KEY}
  - model_name: openrouter-openai-gpt-5.4-nano
    litellm_params:
      model: openrouter/openai/gpt-5.4-nano
      api_key: ${SECRET_SENSEI_OPENROUTER_KEY}
  - model_name: openrouter-openai-gpt-5.4-mini
    litellm_params:
      model: openrouter/openai/gpt-5.4-mini
      api_key: ${SECRET_SENSEI_OPENROUTER_KEY}
  - model_name: openrouter-openai-gpt-5.4
    litellm_params:
      model: openrouter/openai/gpt-5.4
      api_key: ${SECRET_SENSEI_OPENROUTER_KEY}
  - model_name: openrouter-google-gemini-3.1-flash-lite-preview
    litellm_params:
      model: openrouter/google/gemini-3.1-flash-lite-preview
      api_key: ${SECRET_SENSEI_OPENROUTER_KEY}
  - model_name: openrouter-google-gemini-3.1-pro-preview
    litellm_params:
      model: openrouter/google/gemini-3.1-pro-preview
      api_key: ${SECRET_SENSEI_OPENROUTER_KEY}
  - model_name: openrouter-google-gemma-4-31b-it
    litellm_params:
      model: openrouter/google/gemma-4-31b-it
      api_key: ${SECRET_SENSEI_OPENROUTER_KEY}
  - model_name: openrouter-xiaomi-mimo-v2-pro
    litellm_params:
      model: openrouter/xiaomi/mimo-v2-pro
      api_key: ${SECRET_SENSEI_OPENROUTER_KEY}
  - model_name: openrouter-z-ai-glm-5.1
    litellm_params:
      model: openrouter/z-ai/glm-5.1
      api_key: ${SECRET_SENSEI_OPENROUTER_KEY}
  - model_name: openrouter-anthropic-claude-haiku-4.5
    litellm_params:
      model: openrouter/anthropic/claude-haiku-4.5
      api_key: ${SECRET_SENSEI_OPENROUTER_KEY}
general_settings:
  store_model_in_db: true
  store_prompts_in_spend_logs: true

router_settings:
  fallbacks: [
    {"openrouter-openai-gpt-oss-120b": ["llama-3.3-70b-versatile", "openrouter-openai-gpt-oss-20b":]},
    {"groq-llama-4-scout-17b-16e-instruct": ["llama-3.3-70b-versatile", "groq-deepseek-r1-distill-llama-70b", "llama3-70b-8192", "gpt-4o-mini"]},
    {"llama-3.3-70b-versatile": ["groq-deepseek-r1-distill-llama-70b", "llama3-70b-8192", "gpt-4o-mini"]},
    {"groq-deepseek-r1-distill-llama-70b": ["llama3-70b-8192", "gpt-4o-mini"]},
    {"llama3-70b-8192": ["llama3-8b-8192", "gpt-4o-mini"]},
    {"llama3-8b-8192": ["gpt-4o-mini"]},
  ]

