apiVersion: v1
kind: Secret
metadata:
    name: dr-guard-aws
    namespace: sensei
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:evE8m6o9qIPRHXRBmUB279rloc4=,iv:ab1NKt8yhhHUjDh1ncfFg/RR6bxufC5p2/r1qgNxuv4=,tag:iFEP0CDdeW2Ij8n829PmdQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:TDU92bl1zke8KqI8UDhaiw63ju1ccGKEtDqRnTKmWLgfgEvtEKEC1g==,iv:BFE3H2BPCYJx2JKWomQMv/Abd5vN3HIneapcQqPUj1k=,tag:f0ApuJwXyBjSsMIxmXIeBA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMmllNGVsZ0l2UzN4Q0cw
            djRCWmZZeFlNSjdCSXhWbWFoOTFJUzVwejFNCnpUY0d6a2pINEk0eGtDRDFMRWU4
            eWp5VEFVK1h1VTVsbWozV1pEUXlyTkkKLS0tIHFQdzBZaWhPRHV3aW1sUlNNR0dX
            eVZSRDFGWUFDaEhLYlJ3RkRUVFM2Q28K5wyX1el2A3W3mbwDtNx9RI/kbqQph47d
            pCEPc4FOTn8PaQjkYRBVgr1V75xEDk1xgPp1pbd8pGYF46LXU0XdgQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q6l62kwaly44pl9vwedqvxtxv0fsndtq53s6kzclsccslne7cpfs2352vr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T18:35:25Z"
    mac: ENC[AES256_GCM,data:+8rs1w80prTbiZCzh4RzvEqONWm8FLUVeTv2Ccr4IBq+tl1cjMIHoYjnEqSzbnBwHas9IKTrqv+5b4xKCw4N+Ypq0FjlgCEyDlUXC2V9h/9GyE/H5yhwsI0JYGZhmpPzMs8nuweMR1veumaDYMVC2+4Fu2MZb326KECH5R5IEdk=,iv:7WrMx5KwZ//r2yq5N34p/dfRe1UkWo8J+h100szvq+A=,tag:SlUizivDah1ptP9hX+1PPQ==,type:str]
    version: 3.13.3
