apiVersion: v1
kind: Secret
metadata:
    name: radarr-secrets
## sops --encrypt --in-place ./kubernetes/apps/media/radarr/app/radarr.sops.yaml
stringData:
    RADARR__API__KEY: ENC[AES256_GCM,data:lfwIH+8NmHDY9mi83Uo+baIyZrge2Xb9HvIvyiOoTJE=,iv:XLkOSPek2K05t4iMjmE6JU8jqnQY3vQbL7tsk1pmkdQ=,tag:HXnLJwnUmHxClIyfXpCUWw==,type:str]
    RADARR__POSTGRES__HOST: ENC[AES256_GCM,data:r33sHSfyFLvGXjWEubcX9eGeRtKRQZgYrxH88Ouerze4yJQ8i6ZhOQ==,iv:+zOqq0RYQU/cTL50tJCuIjfbIAelqFBOVvADg/Osss0=,tag:UBjXuFIfLSX3OV/fRcmU1A==,type:str]
    RADARR__POSTGRES__PORT: ENC[AES256_GCM,data:T8+v3Q==,iv:AN23xXMqyI+TkuMKS+OLZogmPjKD6CZH8UZRstZWaeU=,tag:4YzZYPpd2GZls78QcHK9MQ==,type:str]
    RADARR__POSTGRES__USER: ENC[AES256_GCM,data:sjf5o72Zprc=,iv:tNga2fDAnU479vJ7NDapRlO0fJeONhNvM9p+3nBbnMQ=,tag:zARLb3PvCGc77J/V5ZzR9A==,type:str]
    RADARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:d/COVMHy8VLH,iv:4DoNV5lfaKtw7j+Kl9Q/XGDP7EDiu24XnxG/hvX5J4Y=,tag:nZ6aHTPZJQRsaGJcdVxi+g==,type:str]
    RADARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:p28tlFYY,iv:YnfTh7ZKfgkW6ieOfgSWrJ8B8QajTYAcb/MQMCCANrM=,tag:zLCvGlbZmk3SGh0dvqFRWw==,type:str]
    #ENC[AES256_GCM,data:wvWkFwBe2TVcvxlVhVo=,iv:E12zM6KiWuoo3U/rytyPK9mNx9PymSHk1XFoT7F5WIw=,tag:ucamxfyEzIoR2ghNJA+QIg==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:6s+9ihHm,iv:F53wNSgQ/C+3uHHhxCbyPy/EUXg4cbiPBSlteE34Icg=,tag:2oyUIUYyJL+fY3AzxpAMLg==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:zzKn1FauYoNlqZR7CXeZ8JibninKgX1Gt6sQazN6NSQ4x35FlXodgQ==,iv:CLpC1YNf1DnW6LAMl9YvbberkVmhOaSfAL1C6neaQQA=,tag:jsUMgpRPnVrYJsxJYph+UA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:rAZks1ixv/U=,iv:xLbukmTka3pw0V9jurcGX5/iuDogQo3Hc1F/kSCgbq0=,tag:sX8eLuzHijrJKV2L+apVDg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:VPgwUl/DBPfc,iv:KsDjHjGbKHx6/ucntEbGGPJKAsthvaNhhPndeZPTHp8=,tag:qNq7Gfj7yqBrZMQL75Bx7Q==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:luo/5fx1reDh,iv:pRgr0zghRcqCeE0mA/1uTcSq9pws0evGwa16K5YEwu8=,tag:eZ9OYBSwgUzEczts+7TRDg==,type:str]
sops:
    age:
        - recipient: age1q6l62kwaly44pl9vwedqvxtxv0fsndtq53s6kzclsccslne7cpfs2352vr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2amZJVHlhTkgwRy9BazNk
            MzZmWXZXLzNhTTcwM0NEbzdSNXlKeDk1N3hjCndkSHBmaGcyY0lod3JvYWQrTmZN
            RVd0Q0lPOWd0ZHNFZjdiNXZndFdrZ0EKLS0tIGJRdUFScFVOQXJhSGJUT0s5cnZM
            TXNQSEg1clhrUlVMN1h5OVhLeE1kYkUK5BOJmomhWATN0lH1sd+IeODEdTxGVFVq
            LhS1/N0j61wIwKHzeDdOwMlUFbMy6oiMxnIXra6+E8aKkJQzO2VKgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-19T21:32:39Z"
    mac: ENC[AES256_GCM,data:11uDxVGHe6kVaF0yL40qpt0X1V7Y3e3wsjLuelnT0SPpbxD5He+tngEhdLpy6yPvzZcobXoQch5r0xYbUPm4nhg9K/BUl+AWWRZhyMuwkf2tzv97Ke+wruFkb51kJ0bKD6/gyD06nRQSRJ3grefDWX8w208RIqvb9ijus/B08rQ=,iv:IxFENx4y1w/ocnUatqWBoAp6Be4+1vqVOXDi9mKi5Wg=,tag:LOOCCGlFhII8H2KYL+9Jyw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
