---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN/./-}-production"
spec:
  secretName: "${SECRET_DOMAIN/./-}-production-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN}"
  dnsNames:
    - "${SECRET_DOMAIN}"
    - "*.${SECRET_DOMAIN}"
    - "${SECRET_DOMAIN_TWO}"
    - "*.${SECRET_DOMAIN_TWO}"
# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: "${SECRET_DOMAIN_TWO/./-}-production"
# spec:
#   secretName: "${SECRET_DOMAIN_TWO/./-}-production-tls"
#   issuerRef:
#     name: letsencrypt-production
#     kind: ClusterIssuer
#   commonName: "${SECRET_DOMAIN_TWO}"
#   dnsNames:
#     - "${SECRET_DOMAIN_TWO}"
#     - "*.${SECRET_DOMAIN_TWO}"

