---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN/./-}-staging"
spec:
  secretName: "${SECRET_DOMAIN/./-}-staging-tls"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN}"
  dnsNames:
    - "${SECRET_DOMAIN}"
    - "*.${SECRET_DOMAIN}"
    - "${SECRET_DOMAIN_TWO}"
    - "*.${SECRET_DOMAIN_TWO}"    
# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: "${SECRET_DOMAIN_TWO/./-}-staging"
# spec:
#   secretName: "${SECRET_DOMAIN_TWO/./-}-staging-tls"
#   issuerRef:
#     name: letsencrypt-staging
#     kind: ClusterIssuer
#   commonName: "${SECRET_DOMAIN_TWO}"
#   dnsNames:
#     - "${SECRET_DOMAIN_TWO}"
#     - "*.${SECRET_DOMAIN_TWO}"