---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fief
  namespace: sensei
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      fief:
        replicas: 1
        containers:
          fief:
            image:
              repository: ghcr.io/fief-dev/fief
              tag: 0.28.6@sha256:b42dd251a734be308ecfa83ec05ad0be4f096bae28cf91972de3a12f366e364b
              pullPolicy: Always
            envFrom: &envFrom
              - secretRef:
                  name: fief-secret
            env:
              EMAIL_PROVIDER_PARAMS: {"host": "${SECRET_MAIL_HOST}", "username": "${SECRET_MAIL_USERNAME}", "password": "${SECRET_MAIL_PASSWORD}", "port": "587" }      
          worker:
            image:
              repository: ghcr.io/fief-dev/fief
              tag: 0.28.6@sha256:b42dd251a734be308ecfa83ec05ad0be4f096bae28cf91972de3a12f366e364b
              pullPolicy: Always
            command: ["fief", "run-worker"]
            args: ["-p", "1", "-t", "1"]
            envFrom: *envFrom

    service:
      fief:
        controller: fief
        ports:
          http:
            port: 8000
    ingress:
      fief:
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN_TWO}"
          nginx.ingress.kubernetes.io/configuration-snippet: |
            add_header Cache-Control "no-store";
            add_header Pragma "no-cache";
            add_header X-Frame-Options "SAMEORIGIN";
            add_header X-XSS-Protection "1; mode=block";
          hajimari.io/enable: "true"
          hajimari.io/icon: mdi:math-compass
        className: external
        hosts:
          - host: auth.${SECRET_DOMAIN_TWO}
            paths:
              - path: /
                service:
                  identifier: fief
                  port: 8000
        tls:
          - hosts:
              - auth.${SECRET_DOMAIN_TWO}
