---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mfsoft
  namespace: default
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 30m

  values:
    controllers:
      mfsoft:
        replicas: 1
        strategy: RollingUpdate

        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/clarknova99/mfsoft-web
              tag: main-e2759e370f21d7c2a0705bff38e414727820e213
            resources:
              requests:
                cpu: 5m
                memory: 128Mi
              limits:
                memory: 256Mi
        pod:
          # imagePullPolicy: Always
          imagePullSecrets:
            - name: mfsoft-secret
    service:
      app:
        ports:
          http:
            port: 8000
    route:
      main:
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN_THREE}
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Infra
          gethomepage.dev/icon: kubernetes-dashboard.svg
          gatus.home-operations.com/endpoint: |
            group: observability
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https
        hostnames:
          - ${SECRET_DOMAIN_THREE}
          - www.${SECRET_DOMAIN_THREE}
    persistence:
      config:
        enabled: true
        type: nfs
        server: 192.168.1.3
        path: /volume1/network-storage/cluster/mfsoft
        globalMounts:
          - path: /config
