---
# Sourced from cluster-secrets via Flux postBuild substitution. We
# materialize it as a real Secret in the sensei namespace so the
# license key can be pulled via envFrom/valueFrom — bypassing the
# bjw-s app-template chart's `tpl` rendering, which was rendering
# inline ${...}-substituted env values as null.
apiVersion: v1
kind: Secret
metadata:
  name: temps-maxmind
  namespace: sensei
type: Opaque
stringData:
  license_key: ${SECRET_MAXMIND_TEMPS_LICENSE_KEY}
