# https://github.com/Tzahi12345/YoutubeDL-Material/blob/master/docker-compose.yml
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: youtubedl
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      youtubedl:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/tzahi12345/youtubedl-material
              #tag: 4.3.2
              tag: nightly@sha256:ca6f08a9c3aeca75ddee7356252fb712998f45e99da9542d0e14c2eaef5e8e08
            env:
              TZ: America/New_York
              write_ytdl_config: true
    service:
      app:
        controller: youtubedl
        ports:
          http:
            port: 17442
    ingress:
      app:
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: youtube
        className: internal
        hosts:
          - host: ytd.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: 17442
        tls:
          - hosts:
              - ytd.${SECRET_DOMAIN}
    persistence:
      config:
        enabled: true
        type: nfs
        server: 192.168.1.2
        path: /volume1/network-storage/cluster/youtubedl
        globalMounts:
          - path: /app/appdata
      media:
        enabled: true
        type: nfs
        server: 192.168.1.3
        path: /volume1/network-storage/Video/youtube
        globalMounts:
          - path: /app/video

