apiVersion: v1
kind: Secret
metadata:
    name: sensei-prod-daily-refresh-secrets
    namespace: sensei
## sops --encrypt --in-place ./kubernetes/apps/default/authelia/app/authelia-secrets.sops.yaml
## sops --decrypt ./kubernetes/apps/default/authelia/app/authelia.sops.yaml | kubectl apply -f -
stringData:
    GROQ_API_KEY_LLM: ENC[AES256_GCM,data:AvttGlBAYgys8jKsJyEm+XLdxNDHovvD5tVDJ7hTKn1JoGVTbkKFF57NDqu5KKKNjjx710wmoZw=,iv:B8S01cIAbqZo9xrBVpWa/fu0iGNglFqUu0/BdBqNboM=,tag:7FR4+TnZ31kovg0S5/e/+Q==,type:str]
    GROQ_API_KEY_PGN_TEXT: ENC[AES256_GCM,data:WRiHLEQY7ShjD1fgosSWKlF6ALpdLJnln96epgMjKC/9YEhuDxZllezELdWUi9e0YkWnJkh3hNI=,iv:Zj65p9h7GiUv2CoYpVL6fZrJ8vOviQI3L8/EMjrqG1Y=,tag:FXWdWLL3iQMcdza/g2659Q==,type:str]
    PG_URI: ENC[AES256_GCM,data:OxtBpMxsFd/U6YSLoY2eJNrhEiR8UN09HzYWuYtlFoXG8MCZNZp6KYKFAJnanwkaCso2yMDMvMmuyLEP5Q==,iv:rShq1Hr6DMXpQMvPIFeyXkG5RNVYcAL3MUfdyrFk/zA=,tag:vPlPwR2TAt6ADvW1Qj/iGQ==,type:str]
    DISCORD_WEBHOOK: ENC[AES256_GCM,data:9+E32CO25q5bC/b8Fuer3PSRhvU7yE6IHFIkQZFH0hikuMqyz7t5WUcb2GZREdBhy3shWxYQrf0D9kJTEqiRCIYO0nSraqrVpXq5JN3V47ocmDGRFrn1eL2FLjOZar7r5TcCyKvAbhWD16qQDPJvReWwtj/KADoqKg==,iv:jIjqytgZcPixx3tBn8FEEH9l1eCUDfxqdCuSCGhQTdk=,tag:esGGpLtmp27r+1IWXzN0tQ==,type:str]
    LICHESS_API_TOKEN: ENC[AES256_GCM,data:Ze9VzyUpKkVZgo77x2sWZ6dsHZuuyoC8,iv:eMv5aZaSZDaUf1fR3CGDNJQ6fkaG0fRjSwyAgQhfpQw=,tag:IODPWcIrCL3bD1OkHgxw7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q6l62kwaly44pl9vwedqvxtxv0fsndtq53s6kzclsccslne7cpfs2352vr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvUURYRGpycEFVclVsTTl4
            SndMa3ZGam9HVHZEbTlLamxZKzJjSk9QTkNJCmhwQWZsVm1tc2EyZ1RxS3g4aVZv
            ZUJPVHBHM3MzamVqM21WWTk1TXJTSUEKLS0tIEhwUHZQWS9BRlgvRWxJdnl2REVy
            TExSSTNXVjJuak95OTFaNFZIMEhuQ1UK+WGgrUID1FGqegMyoM2DFqoGOOHIiBgx
            wrNKabS7994K+HdWmzs0iCAOUWVrZ+cOLqw2n4oyt1G9TtkReoOY9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-08T19:42:58Z"
    mac: ENC[AES256_GCM,data:WCLTthh3mRcSuiDI2KXY9MzufnX9SDmD9UbHiD73M8OWcrgABh1KlK5Xx9UNajow5JydyOZUo+EALJVm8KgFcJXonLBTj3ltYm8uP4HXNIc1yIIC1Bmg7vtOf8MHu0Ga8tpgREHRKFFjErstIB4P4ssQ83WFG8QuhEasBJI3UPA=,iv:voV3aUnb7eoXjRMrpdLgntIo0lTXM+rLFx46vYo8xaM=,tag:4I0HlnDyJ8snh0ScFtK+PQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
