---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
# configMapGenerator:
#   - name: adguard
#     options:
#       labels:
#         app.kubernetes.io/config-owner: adguard
#     files:
#       - AdGuardHome.yaml=./resources/AdGuardHome.yaml
# generatorOptions:
#   disableNameSuffixHash: true
#   annotations:
#     kustomize.toolkit.fluxcd.io/substitute: enabled
