---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: sensei
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: redis
      version: 19.6.4
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  values:
    architecture: standalone
    auth:
      enabled: false
      sentinal: true
    master:
      persistence:
        size: 5Gi
        existingClaim: pvc-redis
      service:
        annotations:
          io.cilium/lb-ipam-ips: "192.168.3.60"
        externalTrafficPolicy: Cluster
        type: LoadBalancer
    sentinal:
      enabled: true
      masterSet: redis-master
    service:
      annotations:
        io.cilium/lb-ipam-ips: "192.168.3.60"
      externalTrafficPolicy: Cluster
      type: LoadBalancer
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
