apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:76VX1xlkz0BeFks=,iv:+rk1bk32gZs5cdzdbxw0uhWLPqDMDRNOS5Lvm7Bu8MQ=,tag:3qUko0+7Nk4wg7SkxHboSg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:8i8NXvJUL37E/Nvjj46iMjY0q61K,iv:Awr6mKPss7oA2iSlaFGIF9eC9pN157uSGnayyboOk0Y=,tag:psKNtLfb4iUWK5yG3jpoZw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:N7IRoqFpIxcMrREWJScM0+ABNYH119dQIuwBtsOqGrLhuQ+g,iv:k3qClHUBJlS0Yc1horNdgbSMglzJ1mQdyflupog04GU=,tag:F9lZFdoTWfSGpGVPfQvkig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q6l62kwaly44pl9vwedqvxtxv0fsndtq53s6kzclsccslne7cpfs2352vr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWHJIcGltdkJ3RmJOSXln
            bVBFeVFFK3paY3lMUE5HYk1YdkpHL1I1TVh3Cm5PaHhRWlRkRk1OY1UxQ1pERE5a
            NUJTYzdFTzAvZitDSTdvekVZWUoxT2MKLS0tIDltOUFkOXp0VDJEQWluWDA5bDFK
            WmtDWWJXN1p1dEhoWkZ1endyWDgyc1kKOw/s4roKTR9LYVAGM8gMvKsM/QqcNcsf
            nkbKqqzZo+AcW1CPVZjXvh2atUthoP0mugKK86bAS7dC9GqLtFSvyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-18T04:58:05Z"
    mac: ENC[AES256_GCM,data:tNjbOA3Sg5tmolekzd9/3m9i9grQK0bfgWrVf+RnHAIB0EEEZRM3VOGXmX5uyYG/lVLow4sNbpzUeu/h27Ypbqx3DiktSAVBS+AI8cXnQvLrs5vm+z5/iPAXR8zvujnA15ERS7XJgJpPc/zuzkG0+o67ZXZKTyXc0UH0GvczZ3g=,iv:zBRxKvHY8q8sWw8AsrJ7C850W1E1UeyOzU3ajEQkxUs=,tag:lBkNCQsgamoAgfT5km8jmQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
