apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:D9eUZMDi3BiXwA4=,iv:qEaOKSJdbO3rztD7+FW2ej5TAQuTI5PSil3sPVjkRpc=,tag:hm37fnX+K14Nk5JYQMnJpg==,type:str]
    SECRET_DOMAIN_TWO: ENC[AES256_GCM,data:FBKdT6qDq44byNfL0+sC,iv:ivFNq8ISymIl0Wv9X2jn8u+/H7R5r/J29JGyLyKnrjc=,tag:dTAzNa0MO/78OJo6VGj6yw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:xOikksnfgEKoIeBXUZR5jBo9UMg2,iv:xpsIqXz3OytKMFm5336E47wdJQ51yO/NebxcdTrE7CY=,tag:Xftd3adMZ4AKX7OqXez6tA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:Jld3YT9g37fuN6ikqabFr7hkz+3uKiADwTgSDZ5q/c5UaYfA,iv:6tvXrOD1JVSza7cBwiVbuQn3e4KoQK3ycxKK+x0BSnA=,tag:ibYdPpY/piJ+SxVuuDoygQ==,type:str]
    SECRET_MAIL_USERNAME: ENC[AES256_GCM,data:dQRpBWlmP6lhWT9tf8QbFPSL8zFmPtNqnCaPxbBfhPQ=,iv:ZAJ/5a6NBa1fXkl9cGlGZiaWbMQ9O2NN4WaVu/1kc4k=,tag:jBJKCq1T+H5JqmfvswVQEw==,type:str]
    SECRET_MAIL_PASSWORD: ENC[AES256_GCM,data:MjTa9Wa3QUiwWhUohNnn7x5Ie/EOibVDtxg75col0+4=,iv:TMwwuJbSOyd8hnjF+c3LAVf2yhdBONvwQpSTFgp9u7s=,tag:oMISbIh4Eh6Zrvn9gA8MPA==,type:str]
    SECRET_MAIL_HOST: ENC[AES256_GCM,data:8KFShq7ix5Vj0i28e71fgI4=,iv:1nFgtstdQxw60k+qYPanUpOgM6N1FcK3cFBPj4i6B1U=,tag:Hrh0FoYNKmj5q5JxIV29/g==,type:str]
    SECRET_MAIL_PORT: ENC[AES256_GCM,data:PN1s,iv:Zt0kufU1gm9t9eW9lBhsaA9VD2dgbNf3gz7GBQVeq2k=,tag:4EjQmyHVU4drJtlXoh5FvA==,type:str]
    SECRET_PGADMIN_USER: ENC[AES256_GCM,data:Ad84iEznbxo=,iv:Zz85tLZBbkSbA2SP+OYG5kVfz4EjnMHLsu8O45YW+LQ=,tag:kBsukTT+Cw9WSNWVWUj6zA==,type:str]
    SECRET_PGADMIN_USERNAME: ENC[AES256_GCM,data:tXlYP3s0RutKDCvK5kzDmjn1U5s=,iv:oCBdVXwN5xCHWFs5ysKTvKvzSKmRNgeZl7Vyn/AxAWc=,tag:MkjdZpKy4KyhjQhE/2cTng==,type:str]
    SECRET_PGADMIN_PASSWORD: ENC[AES256_GCM,data:SE0XkxD0sF/+,iv:rbkjKodO8Zxm8MRYQ2NqpQyrTs1VcpVkJP6nETB2U90=,tag:HVYoo6VHBRnkEkRS6dAX9A==,type:str]
    SECRET_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:L7nFPK4AQ3Ov7azyVwIO9ShrzhW3okesTWYKV+OkgWNyqEkGzFYJW0tci+XMgeMpt4iivHcwz3ybmXEOInGA2A==,iv:ZG279cRyQg7xy+crRi227HUr+gLfr2hC3widw5RhZdc=,tag:sq+BqbteEiSiQLakV/FtEw==,type:str]
    SECRET_OAUTH_GRAFANA_CLIENT_SECRET: ENC[AES256_GCM,data:Nj222Zcjb89Vkbew56CJ106CwvBAMw/u+wMWNAhQgxnzb8CiY8rFC7fevPTfiy34adHp7b4ZXyIaSvL+6mJi7A==,iv:70fyXUFNXjOQlvTsant+OAm2z8jngtWr2kWO6nUQYgc=,tag:krxFxkSsItVW6H/tSAsK6Q==,type:str]
    SECRET_OAUTH_MINIO_CLIENT_SECRET: ENC[AES256_GCM,data:nLe1ICPYGx994VdNCL13cDP8e6/wAVk6Buc3W4aGg41ogvSmhaSmby9XsfeHwq1y3RxzzHi5CizaLTYONFPSYQ==,iv:rrQjpP3vvKmnL6QQiv5Pb108oc9/XrgezWm0M17lZSQ=,tag:kHlegF/MgYRd1wIUU/59SQ==,type:str]
    SECRET_MAXMIND_LICENSE_KEY: ENC[AES256_GCM,data:zgsYdzUs8a0w2UUvtFOGe6v2Lcb4lSYh05iSUKs+GWlNTZP0/86Haw==,iv:hSahxXmno7csw8/fyCOr8ZB2s8Yv2c+fDlFw5Mjr/Vk=,tag:GUxAFQRTF8jy/C4wH1h/kg==,type:str]
    SECRET_MAXMIND_ACCOUNT_ID: ENC[AES256_GCM,data:rIWtL+tB,iv:WXZQN10pwt0sdlRkYcH6ilu6Pj2pAWz0XgoB/35kUP0=,tag:98TwjzclbKsKQu+sEvMcTg==,type:str]
    SECRET_GROQ_API_KEY: ENC[AES256_GCM,data:7vvVoVEV7kQCYgVc1OCF/Lq1cJaU2Pr+JJqIYU9KCILkO9n14gGqLMyJwo+JZVUNHqtx6TCutqM=,iv:UJSYwsnGK7c/Bp3rRFbXZHiiumlUWfP+gTyyJXyaFlI=,tag:FmoV3emmOuKRqj34Ue9uzw==,type:str]
    SECRET_FRIGATE_PLUS_KEY: ENC[AES256_GCM,data:D8W0Vkb04046j7XAhyR542u5aZubJQpdsOMR1yZiv0KVyjdjhQKtWZKP468EApkNRcuqBPuKN03zkVc15qHdDUO1YpABqbd28nzn0u4=,iv:ukp9gLNy/7UzXQE65Fmrdns56Wh6tUIgMticgN/9s3w=,tag:68VCN3xwYzxxJ2XuYFxVzw==,type:str]
    SECRET_MQTT_USERNAME: ENC[AES256_GCM,data:Zm2W22ZSqg==,iv:surwWxeG3MWxe1+0QgL+qj7doKZYLOh+jSuPny/MSpw=,tag:LENShzccIJiMex4//8sDdg==,type:str]
    SECRET_MQTT_PASSWORD: ENC[AES256_GCM,data:3ZmbF7IiZoEh,iv:wOkJfud662QizgDk/GebCmeZBxBLk8EbMzXEKCfw88w=,tag:63UGBYNf7j+C0eaFxvy+Kw==,type:str]
    SECRET_CAM_USERNAME: ENC[AES256_GCM,data:BYZrflc=,iv:LnVm/I7M82NDDI+w8TGqn1CKfAl4DA85t6qGisa+pUI=,tag:f0+KXUyGpx7paFhRiE2cbw==,type:str]
    SECRET_CAM_PASSWORD: ENC[AES256_GCM,data:/p9WisB0,iv:PDyBOPbbzR/Ck8qzAbsTfBUmpzRBThKDuOv8kJdNsQg=,tag:eyIRdJZdPTQ+Gh5EKyodqA==,type:str]
    SECRET_WIFICAM_PASSWORD: ENC[AES256_GCM,data:cc3VoFNPqhmM,iv:OhdbcaHxr4MXBkkWNSToGJhjOc0TNxOPnclP+IoCKqw=,tag:LnzcRAXpV6cZ0r0dz87yUQ==,type:str]
    SECRET_BACKYARDCAM_USERNAME: ENC[AES256_GCM,data:cj0UGWo=,iv:ClgAGJ7QBxuIlK/Fn772U39uzb7W1Mv1lFzVVZMB6Cw=,tag:XRS2qwvKhZWLUNiR1nIscQ==,type:str]
    SECRET_BACKYARDCAM_PASSWORD: ENC[AES256_GCM,data:aCyq7+A=,iv:zY4iq9+RGcBZO0LxNBrbNdyl6g9RIEe8kb+RpEH6EDE=,tag:kwksniQRZUoUZGQ+xDSUuw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q6l62kwaly44pl9vwedqvxtxv0fsndtq53s6kzclsccslne7cpfs2352vr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvRlFrbzVpZTJxVjA4M20r
            SDFub3Jpd3d4VDdReDV1WVBTT3FTbTJtWkNjCjQ3Wk5rQi9NNTNLeUJhT2FKSDIv
            d2VEcHpJQkJiUXdBOUJQbHFGaVNlVzgKLS0tIEtPVUZXUWJVU3J4czhVVTN2WFow
            OTllTTEvbDRuOXJQWllaN3JFMlhMbHMK9P95LzkfBbd2y/0oW19YmwUsv649j8Vz
            hJLORyIRZ/cy15TjVtBzKd8blsxJazilHa1XcPhXpMFejk48RmSZCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-13T18:07:00Z"
    mac: ENC[AES256_GCM,data:kmuS3fgkrimUbLsMOZjNt6uhKPLASFchVNPVMvBsBUkEYjyE9kbGxTRbau5fsXwZtokk1dHmm5mv/9GUm046vmN3B3pOBqu4+Lz9G5H2fDyhZDuFpcAZTr+OkceGKayLybs4VpHiR5M08Qo9Z75ap52DfKyzdufV8qbh603lz5w=,iv:niwsetn/6U54wJGvFh1Q5nTK9xzk4mI128NPVs8Eceo=,tag:0xj8xFdHxULa59r3t2987Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
