apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:WvlXvUxTf8KcH/I=,iv:KXO1rvAzYfwZhavkCc2K1bMK7pIhW50cVylo7iobWuQ=,tag:gUFqiqAPEH9QdCCCL3C2RA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:43KALa1QuVfoRhqaHjj6Ohc7TUEF,iv:RAC4m4yDIH5a/MzWfA3gJidt9kixhTk1YjQBhESZfFY=,tag:kidUh91zG8P+9cbvnFcdbw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:c6Gpa+L9CvoINiMDeu5OOnOFtLEMkwKtCrIpr8uzqU7zMvjg,iv:JETGt537XBuuleRAyeGSC/0rd/ojG62oYX3O8NHYf4I=,tag:PSnpBiBB3LhVpKI508marg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q6l62kwaly44pl9vwedqvxtxv0fsndtq53s6kzclsccslne7cpfs2352vr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZHlOejhPZGd2RUltNnRW
            OUdGYnhIdktXVGZKdHZWQXFwN25YWWhuUjBRCnY2VGdEM240SCs5UytMbVJVbUhZ
            cjRYWTNUQ2lZMEdwSU5LNXUweUpuWUUKLS0tIEUzbE5LZDh5SUxmS2xkUjNoWTcz
            N2NEUmhWU1o0TzR3aUZoRDVXY1VwVTgK55LXA8ZnClHvbqxRKpB/Rt8n3ywbt8nK
            yU2hiRVXDpQ9PBknkRY7KeH/2RMOKiYyjH/xGOzJ1os16DP7C4WrNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-19T16:17:45Z"
    mac: ENC[AES256_GCM,data:qAwpHzsOFaqJ87baZI9x/LCWqi0PTR3gqQ6GcaWw6lm/lAf4n19EMK488BuyS+bT0Zv1/WkFYIshPMUsGqYMYeh9+ENt/QRwwk5Shk4ZjOs9+9hN7X42u4b4ADUyxuYNc/0WZ0JgCAYp1BmngdjfChYbKxlK2Q9XQ+twwmE27x8=,iv:YYEreErd7U0XTNM9HZ5mP5pNP25oq6KiwZzX/17JZoo=,tag:k2a4u0wZXGu0ct4uyDMFtg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
