apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-secret-auth
## sops --encrypt --in-place ./kubernetes/apps/database/pgadmin/app/pgadmin.sops.yaml
## sops --decrypt ./kubernetes/apps/database/pgadmin/app/pgadmin.sops.yaml | kubectl apply -f -    
stringData:
    config_local.py: ENC[AES256_GCM,data:h2Vt1ZxzZY2rb92xYqfcszQH/0e57eTmHZpk3iLK6us8gVQnO+5rhB28RlFuU2u6s/K22+ONvxTs+lSs2iqM0Geq3y7KIbeovp/5rq6zaVdi8XKVEgF7mQA+yifBAajW2emLwW2C54o+oVX5O0VIz8Rbzp9QUBSH+YvknU6Zg+bRLB0zlIPkCzxrnJLc62eUavGKnnikEyC+ENkiXEU6FCKH2BqHKaOkBZW7mcKbyKvqCWGkhjX37zCvRnSVnVwz28ag9v3v6Iv3C7VPOKyby5xr9kwghtOQQvSEfiQlpTDyE+9e/NCW+peaQ4exeoHSd3aUC2vfJjEyiNN7E1rbyQYtr8fWZeKFyjlaaZovhndl9+hTj3VYeqRhS13Q0z+kUQJOhe5WpuMq5W9Sgf4eUakfIvVTPsl7sx71DW2sVirGOhOwj5n6rFSWzBze11kBOnrUDKuKb1tavRI00LYXkpIuBDxWqJdPncs6iQN29sHDw1h3/mMriBq7bj+dyst+ej/p0WvhIw/lV/XsZo+sd0eiBqTS1QBxLi5B2b032V9qcpy3W0MazrQN2djcBfj09RAMI8NDLUtu8orKi2vSS5TD8ctt6ziwKNjw14EaB2tTBfcEbReYkjSPPnAkLTdODmnot5PxpvrV6qRzEVGNl35Ge6zQu6IMIRQRRfjbN4gmndqbSfGXQvjl9LzEHtkPVU2NisGbgYiW/ddHYr4RVbz2sH5dtsPavh9CVmi75GWl3zO22i0eoX1PG1pmw293IfIwSJ3fjENFE8J6YaOBFM64SANh9wDGGEN+u2N7BeWN8tvlQ4HLJZsytc0HDZ47TnNQLHYd0LVRJZXAPEaynrJ3IbXDBnVCu5aS65BJHVOsrscHJyMANsknxnlrxPOP2X4EXXj7a0MHK5YHK7oNnpCqike7QoGWcpW+kjLxtaiXAy293lYxA8tCYZfvl19SuG0iXpPEumRH8XBz0DxGWFt5m2U5yc0VYhojKUwealmCJCRsHYdiJSuyhGTQH3WT6uY1ZWwRosGuvUM+1iEWvQ/1HVUUBH3rgR1c3e6HVUTG08zRor4=,iv:amAl3qG0RTXVEHBApr+aH5BV88PdqLvugQmCGJ98Xl0=,tag:DArKf/wLfUDzCLv4DK+qVg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q6l62kwaly44pl9vwedqvxtxv0fsndtq53s6kzclsccslne7cpfs2352vr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhTzF0NzgyTVBPdnFOYmdN
            VTdscjliL2JkME1IekIwd3k0RG5HU2ZFeDJ3CmFkcnEvRW9wd1o2WTFqM1JDQ3ZW
            NjNZcXZFaEplUkZBb1FsZHd3RG82ZWcKLS0tIFdQSEt6Tlp4MEFESElQc0lOelh0
            MFJKZ1RDV1hWNWV4WEtoS0JySkh5UUUKI463QS7ue51oeIHJ660i/dAwYdR2I3bZ
            Py/txP+XPVu+B+dcnkfHTUOonxVnGknBfaFasYrRuKjkS9oKSzqDdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-27T17:45:18Z"
    mac: ENC[AES256_GCM,data:VDEC0E/NkVypyAfrgjHgyiljXwH2l9d6GYUEggQXBZvQ2qOFqA/srwVjk1ZLKjV4OY4HOVij1x9EljCsw9mlXtmngJYvvXFkHtUmroo3cxAblTsaJbBXTY0xuau/f+gJnrPLhvUXm4F2W/lhLNgCWkZDVuXzs9Zdvnwq72M0z+I=,iv:C6cVtPPmNjY2Lq8Kn5j7aQLwdBaIBmG/2IUv7bmhIRw=,tag:HP+BgQ1hBrlBhiRW+iTkGQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
