apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-secret-auth
## sops --encrypt --in-place ./kubernetes/apps/database/pgadmin/app/pgadmin.sops.yaml
## sops --decrypt ./kubernetes/apps/database/pgadmin/app/pgadmin.sops.yaml | kubectl apply -f -    
stringData:
    config_local.py: ENC[AES256_GCM,data:lNK6AaHQRY3o59E1zwJ/KQam7AzS0jv7oKyeFurny/A5zCWGMZdyfA3X1guOqPyURaMLXZXZ7ul1KfkWku8J3La6Pvqcc6T1LSeAXsGFhV/TtLtGs3CvUB7mxxUejQ+As6SMISr+vWL8BNI2+uXDBQ+9R8IU74nohuQ98c2vxlj920YpmdBO5KaauKOEJhGzDEjahWcLe65Rcr5rL4DHS9xtj6hiOqiXPfBgF0xQjCTCdV170Io9QByfpRz/AAeoZTTE4Bi3xXExmB90lMgebWlGNW7AQDOYhEnqaxF4wp1I2AqnCxTjmpZjqSgD1LURZ82vibhvQspW3L1kKlp9hCacm04J4eqKmUr8O6u5MKEd6Apn1sLl8kDPhYM2o0UMVqykocwiC+I8DghCo8Yny54y4rQe8s0RHlZ8NeB9Y7TBLXkU8fp4SNVGtAfvn4Lzt6DaxR9aBIIpC45IBgJgi3KLJIrf2CNEUZdXZaRHkRsroz1IKknhcRT8NDHMxkeMJXhCKEHB/6u/SOGz9UjX3pH5n3D20G0lPpm0G2rJyoVzVzvZBMaPuK4vqMPR14Yp2PH2FGJDRe6JXTsbN9yGXEM5teR0UdZ761DqCtA76McIztrAYJFyhaPxp2r5/b5Q4fnofjaQNF7AAnuyIfajrjq6TW1DOxlnK1ULOw6SeCBggzk8GUTeXMKusXPRfahid8S7SmmOHaJ3NRGXb7Hh9sEUY4jQJtlGK9xCzhBgNpIE4KJBQo8m8q+yybiiH8sKQ8FSjBZ666PFCXRICwaV1BAXbnZ7RRwd2p2Xhcx0EpLOd5c0ZhmmZh8B5MJvuOydENBrcVy5+ghOzHk7GRFMT+wdcRx8/bfOWLQUy0N1LLcUlphIiJ2iawvuiuEo/vJnrVQE0M3yTdKBrsbZu0ONskq6tKuFIvLhyj4Q8Scxxmdb76XsdXTWpvSZNg4uiJQ/HI+r5fHGr272xD7h7FQ5KN39usKQ+sODygbqDra4aKfYRoIOTBMf1eDyj77HTBqR2EqYvD7QMTNMzJkfLKZHmCMnxc9UF2/sG9GYfoIX0cJpSZfvY7R0OzwPKg==,iv:bet/JLbXmY0MsGYO1cjtBKR/sda3LmuVmwn18qHP8tw=,tag:A8NLkn2Y7guiq7SnRkVDYg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q6l62kwaly44pl9vwedqvxtxv0fsndtq53s6kzclsccslne7cpfs2352vr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhTzF0NzgyTVBPdnFOYmdN
            VTdscjliL2JkME1IekIwd3k0RG5HU2ZFeDJ3CmFkcnEvRW9wd1o2WTFqM1JDQ3ZW
            NjNZcXZFaEplUkZBb1FsZHd3RG82ZWcKLS0tIFdQSEt6Tlp4MEFESElQc0lOelh0
            MFJKZ1RDV1hWNWV4WEtoS0JySkh5UUUKI463QS7ue51oeIHJ660i/dAwYdR2I3bZ
            Py/txP+XPVu+B+dcnkfHTUOonxVnGknBfaFasYrRuKjkS9oKSzqDdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-27T17:08:11Z"
    mac: ENC[AES256_GCM,data:5IEgXnZq3ahyghn5i4uyikoyYnC1eCCOFfl763I4NMP9o0G2D11xIiL86gWj1yB/6mEpTIP2cay2TjDbSY+16FxIkChM+neYbksjVwxcvb1ARZNqyZnsGC3O6S+A8CIIRhmJTX++b8111+68LRb24wkR8KR5f3wX8Gn3onZX1M0=,iv:64rtWK6r8hlqnXt1cjPGU7OOHoqq38SgOscuQhwEK2g=,tag:7771GYaA2ZV0+394DOwaFg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
