apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-secret-auth
## sops --encrypt --in-place ./kubernetes/apps/database/pgadmin/app/pgadmin.sops.yaml
## sops --decrypt ./kubernetes/apps/database/pgadmin/app/pgadmin.sops.yaml | kubectl apply -f -    
stringData:
    config_local.py: ENC[AES256_GCM,data:dSeRIOo5Rt90SaefFvTztxIt1Nqn2pUuyb3RXElLdJExjXuvFH3nN76fcY8J30al+f5njrzoQd6kms3JV4/ga1st5jlWkHZ+1hDLqoWryEz3k/uPQBtA0zcOfhmDeijPH4xL1gEH1Sxa723P2KJ43BR+3+htkRffv/5McZSwB+HuYXlZnw/ZeMnt/AV9Y5NQPHGFOUIjD7lvmBUNnk1LJfbJteTkG4+KgVtiKRWik0Lr54PfXLFENgBzlSHFqR/NVZHVZAqDlMmjFp79V60RJzz4yLyRLIXuHopVwbf3bim7zhweUBzy3JSVz0jP378mlfJfxceRAcaDVE/RnBCU95l+W7jF6+iKizw62e2kXT0uxLib7jwcxIHJxK6eLMZFyG4Sd3tiJptOJ6U5FeuTiAaNyWlMqfVqCGiRPtJIsQ16PBhNgV+8Qas+aWChX4TC/h01vaHrLKN4UgnCsorlK98fDfg8gB1IyNwXtW7P4jl7wFswss0zfI9Zh89p7uUg4oXGBkHkB6JJRvnkQpx3olLvOR4+umbB+ii5i84N2YC4dxOjl1vAnQQhE8lg9jlO5mEDaHzjIsMvqEcT56U+dBnnAbRuxDqpk9roXcbNV7lVUUkYezuXPDVgQOPcAuESO/FXaIc73K8djEh6V8UVTX7i++OjUVzPnpcF9rVjZz6AOk9QnFpXbsAhMOHybIN3gJiK/gbeqbnwfbZTVoHO4Gqusw39xqUmnkRMC5hIDrTUF+LYPvIx2RmLk/ZEIJNA85IvmZ2I0i1JXk8zPSjgUEpBCfIQLeiUnOMUAel2Nk7fEs0KfyH7PX0tl738OaJXpz+pTb31SqevuDM2RkbXth/QqXXxx/Sv2ZThUrxFXfucpDrH/h5jIBqozNXtRUYmdpXE7eQy2PsV86Yb41INN2BZxY8B6oqNgd2j1JzTfluf+cbqr6x8ynV8UGTmXhGNCSf2OqCQvbQcv/oeO49BOCTJ7i5f072f0WIhiX0BSs3JbGlO2mBKgJSnMeVTXv3p4CRjtwZyNF01Gyd1L6w0q0KYqiG7c0Bk/e6Xbh7K1YzvL2qhh+m5l/3Tpw/PW9nx5Kt4HezZdhnIIIBfCGoeo4xTl6ezZATCdwB4,iv:Xrn5KEjUESjpQb8+FrTva34hkxLFR1TMcq1K4Qal/O4=,tag:kcb9HnnLNkTVY1OjG7QAdg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q6l62kwaly44pl9vwedqvxtxv0fsndtq53s6kzclsccslne7cpfs2352vr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhTzF0NzgyTVBPdnFOYmdN
            VTdscjliL2JkME1IekIwd3k0RG5HU2ZFeDJ3CmFkcnEvRW9wd1o2WTFqM1JDQ3ZW
            NjNZcXZFaEplUkZBb1FsZHd3RG82ZWcKLS0tIFdQSEt6Tlp4MEFESElQc0lOelh0
            MFJKZ1RDV1hWNWV4WEtoS0JySkh5UUUKI463QS7ue51oeIHJ660i/dAwYdR2I3bZ
            Py/txP+XPVu+B+dcnkfHTUOonxVnGknBfaFasYrRuKjkS9oKSzqDdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-27T18:21:17Z"
    mac: ENC[AES256_GCM,data:nNs4CTNjPgz/eJ6b7uC+vtiKuHhWaqnYYodaTNEx5h30VvRhkShB946GFcMGT0ureTqKe9Ij2ep9HCQZ3xp7bF/KdSmBkxee6wsHcqhhmv0cfAnSCDVTMN0B4oswuwPujkS2WO+9xf/evIkNo+u8Pz8uerZXOGNMOLNA1eqxgg4=,iv:h1SWZztLBW86IBPkJSlc18/gjBuDIaKNkON+xDxBPUc=,tag:CHa4KLoLsQbCRWXFuwJwwA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
