apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-secret-auth
## sops --encrypt --in-place ./kubernetes/apps/database/pgadmin/app/pgadmin.sops.yaml
## sops --decrypt ./kubernetes/apps/database/pgadmin/app/pgadmin.sops.yaml | kubectl apply -f -    
stringData:
    config_local.py: ENC[AES256_GCM,data:5uXK/wb4VvuPdctElNcUlkiMZYE40etzaXVeALqaZlT2nZoqkqCp8Vbe69yr0z/2oTN4ClQ9mpP/fuq4HO/GjQ4Q+Bj4p73OciGu8XPoGF6GO1jlnxkF/koOjA09iT2sPYg8MgyF3i+Sl4vzhSULWEzvlTBUk2v1QFz/56OZikvucRW5hbuLIrm5o2bBF1zoT24XgIRAZf9XubuUk0xPMoc/KDy3rOnF+kjC5oQK001JBjNyIXixqLbK2wC06bNvRUxIlGRZ1P7hChpgr2tnG2EpTVfoBxCM+qZuDsgZI0uQNtfnDOBEcmuxs68blguAqaKrmHWAJFx5YSGU+0AcuBce3hAt7KokP+e2ggZjuUqrRDCY834zH/snQF3CCVJTlBRJcFwlw5jnPbHmIce9zPEb7QIr3lh7Fx/3yvfpdaz2tZ4KTU+Ks3qImkZiK/AUoxmqg5eMK5y85K27WXjGAEqzCdF20diqo298rgLu4zEOrAgFuMWyvUPCIihRcYq8h9EGC3+lYH344n4Sm4Qu0p9naYA3P9pQXesCDLWP90cmvL2eQCF/L1JM2CmVKOMtfImGFeLRPOivydl+7W8OQQFTiGLgZublSRj/CFfH7vQ899rt8dADHesgSIMTzGz9FwJFC/V3eW4ZKM+OMkrnjHn3aWdda2oRbMIEbXBdO0jWPjXPEM80YT9EuGzUySzrkwlSxyZkh6yPlTEZo4YPY8THsteofMnBr2ToKZSg2e0lx0Q291Oe1Zq6MRwFECP9m5ByHDZIqApzm5zDQC0zE+LwAqcQ6qlzBSElQvS4cuFZfzvVENnG/nN5SMf9uyweGBvD0q19eo0yGqEYxJDp6ojEgNGMOG+qkwU1xVf+bONr0osrurNi1yq0wSTPnezKI7vxwaKs/Ott9yMIdpfmPr5saoYCKyF5DPLZa++KICow0f5lrelOw4dzmEz6TJ6BphYqEipXxjwtk+tXfFOF13j6ZZHDiF2HUU5FKyqm+w+pQWCns7aZFgBwXc50Yda3JKGqi5i2fFskgmajhmgQNhHQ+pk9VIGHf/XRuxeEqvxI5lKW7jIK0esW8beAgaqZtzTOOd5WpIImw6WhGgzlXNlmZn6wKXAWbq088Q==,iv:B8Iaq0K5Nq0PK0t7EqY7oeqEvCO2Elqgy6PLvL7PvEk=,tag:B+qRBpmAT35/5KTlgW+DYg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q6l62kwaly44pl9vwedqvxtxv0fsndtq53s6kzclsccslne7cpfs2352vr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhTzF0NzgyTVBPdnFOYmdN
            VTdscjliL2JkME1IekIwd3k0RG5HU2ZFeDJ3CmFkcnEvRW9wd1o2WTFqM1JDQ3ZW
            NjNZcXZFaEplUkZBb1FsZHd3RG82ZWcKLS0tIFdQSEt6Tlp4MEFESElQc0lOelh0
            MFJKZ1RDV1hWNWV4WEtoS0JySkh5UUUKI463QS7ue51oeIHJ660i/dAwYdR2I3bZ
            Py/txP+XPVu+B+dcnkfHTUOonxVnGknBfaFasYrRuKjkS9oKSzqDdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-27T18:07:27Z"
    mac: ENC[AES256_GCM,data:aAIf+LAWqFq9j3fxuEAyXPkgb27ABU2YOQgKQZQFwwsNqCI48GSR9yRFOsqJsEr/o8PjUpuk3gA89spl4Lht3nfe1WPdQ8QvHm5H/FUpfRSggZA7YZr6oOMSSoQ7RsCzN/nDlwN/eeVh6yEB0OqwgjBcz6ZfMRBePc9oJ9y6bCc=,iv:jAWRePX5ubEvY/qurZybZ5BwgsNU4DVgZIrVEtvQROc=,tag:jVxqq7hY/4RijhO8fDlvLQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
