apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-secret-auth
## sops --encrypt --in-place ./kubernetes/apps/database/pgadmin/app/pgadmin.sops.yaml
## sops --decrypt ./kubernetes/apps/database/pgadmin/app/pgadmin.sops.yaml | kubectl apply -f -    
stringData:
    config_local.py: ENC[AES256_GCM,data:dVOo/quw0MVLstHqwJPGzHnWG0vNLWgz23rbGraBLO/s/PVcKksdcVOP4Hdx1IpKzNOQvUS++pJhTTfJk6G6dijlX3K52Lmi7qVBuPuydZY1HCfBMMhNDfeh6JDxZ60M+5atATfysuXS4rjRLIQP548EZ8oFBDsV3Ew+ltCkt22yJ0RBpN8qyfVWnT2PXA1e9kuC1UPDxAhjhjUFx3l9wm0pze/+m9xPMCsnUB6yr+R/FynYSA3MacRJ/JQmW18oXS4EqoFzzwzCyPOim6yl6Imdq/j/om4SaotNBm5rjcFErbKG+Vvyo3c2xOSeAsuDxPkcsUDR2Kcjj0sw1oOhiwwFYTYGFHd0bg59sSu1KW+wNA5f8+cOMhxTQI6+AdIEorcUFcg+l1cQ7RrhSculGbJc7nVHcaDB/7Shr8zH1pLCbZSXMQml4Mr8U/yqZz+/1V50hYDYRp/Yd4sl6gxYiUBkfTM3OvTx4tPD2IR/sYRX7rvGrulfhl1vuAxsBo4kgLvPnVITnA+nzHjYrToV7+E7r1xwi0KsDwG/bnicFbpQ6nauZAQ16iRyo4H841Cpc5FhgV60QC9j1ddxRAs+7KpFsCZANNIBiVl1KDxdUIZvoRgSsJV1ZFJTDYM+y9/eaVA7cfUv/4E8ESMDpTnwe5bMKBGlRbFUjH31ov18EgQyR0dIjdzwwY5AbHq2f+g2ONeeiQMTt/pdcQSgBTmYlOCXeRD5NAt7k12omercz/yz4CGMMruuq8G06ZqA1dO7nySbwTAHBBgUf4JA+lW+Fv+a4Ie29nfVv0o0GdQolbuegM4Yd7RAQXPqejEv1zuIecPTpMssgpdhNA4ZX9PAAPCtOko8qG6B9WdLVdjhdo1Ailsq8yQbEFaDP+MOnHOMuOSW9CmwHxj+so4+P96J3v0htD1lmqqF0YBKj/bTrH4IqrCFxcUeSV/GVwd2Ghj477ZpZXufOOzj08JkK0ktZ5YAO7V0jq6ekN82JyAoxolcI61iQ5DHDz8Gcyua81/RlGq8c9SHT1pMrkZL5X4gol9HdtRZAIDUT75OusK7sA==,iv:+wm+IUv+qvAKfuUCSo0cCZKqOMI+oeA1xG3F0jIMbOs=,tag:E/kP6kOkQ55f62uEFixL/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q6l62kwaly44pl9vwedqvxtxv0fsndtq53s6kzclsccslne7cpfs2352vr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhTzF0NzgyTVBPdnFOYmdN
            VTdscjliL2JkME1IekIwd3k0RG5HU2ZFeDJ3CmFkcnEvRW9wd1o2WTFqM1JDQ3ZW
            NjNZcXZFaEplUkZBb1FsZHd3RG82ZWcKLS0tIFdQSEt6Tlp4MEFESElQc0lOelh0
            MFJKZ1RDV1hWNWV4WEtoS0JySkh5UUUKI463QS7ue51oeIHJ660i/dAwYdR2I3bZ
            Py/txP+XPVu+B+dcnkfHTUOonxVnGknBfaFasYrRuKjkS9oKSzqDdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-27T17:36:47Z"
    mac: ENC[AES256_GCM,data:Z+K/f3usuCngaDKXWhSVpXryg4nuWAYVCmGofEh9yDYSyPpgLPXmKBVoj3j+jWhsEElvPGGED4EdMqMt7MD/at9TZ/Qcb2fraO6Ktg8zE6rvVgg44flWYpYeUSYvuk1/2fcpQ8FNNiqiQ/PIewVkX3Viqu4Xh5ml+z/w+pV7+Yg=,iv:wETxi36jHv0fxCsgrRy8/n9C7RTK7DizfPUMPeib0bM=,tag:Dc5cnH2a1MX5KseJpI4L8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
