---
apiVersion: v1
kind: Service
metadata:
  name: postgres-lb-vector
  annotations:
    io.cilium/lb-ipam-ips: 192.168.3.42
spec:
  type: LoadBalancer
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres16vector
    role: primary
