apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secrets
## sops --encrypt --in-place ./kubernetes/apps/database/cloudnative-pg/app/cnpg.sops.yaml
## sops --decrypt ./kubernetes/apps/database/cloudnative-pg/app/cnpg.sops.yaml | kubectl apply -f -    
stringData:
    username: ENC[AES256_GCM,data:mAqiXG9+4lM=,iv:3v5OsVioGeRtON7e5E8s0S48eSFimyGbFsLXYDcOlIU=,tag:fpALDQTTUTEsbnhSplGLAQ==,type:str]
    password: ENC[AES256_GCM,data:cGE8SdUPgXmJ,iv:nLa9Kz2H8V5rNZUwjU8SZ+5O4ZaeqvGjX9gf9JbTe+0=,tag:qLmdBODox7xh3DU1TAXdag==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:wqaajyTsvrBiCu2o8yRzBEPo8R4=,iv:4R6q9hwfvCwEAPf++rHWAEBWtjA9CTxMKTeH2GNaGyc=,tag:+0MbfbCjz9VIlugOZZUAgQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:h4U1GBuWGurNn/CO6XlU6klt+YTuLIqFYRCAs+7eO0Y2YW5iAmv3mw==,iv:4z02SI9FA0E55kGrTekpKLtwmMjf6F0Ao5fzJw6REV4=,tag:RNK0nP86I7pVlHKzOzJbug==,type:str]
    POSTGRES_SUPER_USER: ENC[AES256_GCM,data:2Ns4oBpycLA=,iv:eMk4QlsFqC2Luaug2fqOvnG1Vk29uxCsXTkREJaSe1I=,tag:at2WlmbDnu7atMZccVKb5w==,type:str]
    POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:6jKj9lND669n,iv:5RLXLoplzDgufHzj1S6cr11qp2M4spC40c/9TlasdWM=,tag:R3CZLm41BAK0dTglP3Jz4Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q6l62kwaly44pl9vwedqvxtxv0fsndtq53s6kzclsccslne7cpfs2352vr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZcVlSVkpkdnk3cklqOWVt
            VmpXVlh6aXQrVEhPbTcwRGJZMVRnWmdOT1RFCnlXaHFaSzRVVUVhUHJaeDRJdXha
            V0IwRlJ6Y2lYaWNJRFJlU2RjeGNVT0kKLS0tIDFCL3NuZ1ZzK0hFbmxUeWRVOVds
            cWNKaEdURnVWd3RFYjVPQjhJbzRUaDgKHFXUg6tCGu5FsCQSgPYBj+Vi3BaYJ5qG
            PilpmVCj0PSD+t1eoiXB7NQb9NXxsEkViom1LHdegAwKlsu2ZEz5aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-21T15:36:01Z"
    mac: ENC[AES256_GCM,data:y0XPhQvhBi2FWGQpgOBW/trJv4dqebiQeFK2AOfEv4EJO9X66GoIaUHmBUoGTr+JwaZStAznEeGTGFphDQ29aIW7cw0OEXP65TYKT2OZbMUFtJRmDr0sGJsTnXz2LbY8rGs6Fe79m6e36+r1A+xsWcX7lWszHS3xFzy7M3/RDg0=,iv:cZmRnzGabM7GSJAmeuE2zRLcUbgR0+/oaf98DQ4LFkk=,tag:1qkb5Fgp1/LvecMJg4BI9g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
