apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:DwhWauNiEtnXABL+PJZAUQ7rgbpAVZt5DpE2FCOQgsU=,iv:+aZXZIuGBHTz1LbkJ7CLAH8JaicpQrmbjgOMbYyVNQM=,tag:ZDs98bIesr3xrrFeGnfNBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q6l62kwaly44pl9vwedqvxtxv0fsndtq53s6kzclsccslne7cpfs2352vr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Ukx2ZGpIWjlmckpGdlgw
            MVhnNmRhQlpjWkJYMmpwTE52czI2VkpuWVU0ClNBam1iRjJpZTFXWVJtdmhldGVH
            a09iWWZKUzZka3lnbTNkMHN3M2dhcjAKLS0tIHNQS1NWNVdpT1p3ayt4RDBqajVk
            NkMycEVZaHRJT2dKQlh6VVhUbXJES1EK1JqQUxWtlidKc/nqqPkSw+W//vFDBgLM
            pxd/tUZLjAsyq8qG8LOPJR7x00UGhQMQKKvy1IQHXuMlTSDNV/mzKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-18T04:58:05Z"
    mac: ENC[AES256_GCM,data:2G+vDQ1P2I6NmA2rFUmPpu4AA2MVqh2LU4WU49M+jys69I/2tLyQ8zruUQyztbm+UO1dwki9uyyodnFslKvikSlBO/6NvMbriBr3dRZFJIvtJL0FIlbAH/rxJgBXFOBI6Eukxh8z6f4cbp1ESEqSG7ONtqNasV37KEzMRjmoqv0=,iv:pBUcobxcbYbYjEHxgmQmjXsTPV1sk8mntG2YXuQCXfM=,tag:SJNmlZPQB8Aybo72azNCTQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
