apiVersion: v1
kind: Secret
metadata:
    name: sensei-gatus-secrets
    namespace: sensei
# ## sops --encrypt --in-place ./kubernetes/apps/default/lldap/app/lldap.sops.yaml
# ## sops --decrypt ./kubernetes/apps/default/lldap/app/lldap.sops.yaml | kubectl apply -f -
stringData:
    #ENC[AES256_GCM,data:XExZzIk9iDMoO08G/oY=,iv:6LpcPktVtglrLKgnXPFStb/wtPm3PVN/cly5gqNUkVc=,tag:WYuq6k8miko8nLFkWN38yg==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:vgdgSHc=,iv:fpuHX2Q9IJIoSjAxgvkKLWo5DE+RLocovrrXhOX7wjI=,tag:uMNFc3ODBkMuPpQwbtv5/A==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:0//M2noMKSlphV/Ura1dQVijeDLhgz5wFdUXGWoGaOl8PdNPUQY1Ng==,iv:WD/rG2cYyUXUK4Gano2M+sa2cENfu9kjitDb04UwzT0=,tag:4Dxd47fPtnVf3i3zwL9DTQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:eLRo261i5YY=,iv:pGfC8ci+zU7ZSLDsEqNPXZHaZWj6CWoK0xsrrE8wJUQ=,tag:uhqAjGDXH0wf2YAZVeipDA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:G+IQL7LubtOg,iv:tWt8DUELK/UPGgzS2fZj9sqVusRhUKXcou4tbbtlvEg=,tag:2i7qMBdtqqpNCcgoVXN69A==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:GYomTExXqN9z,iv:P0o5RFHb48MZBr2zAW/XhKDPhWALgOTrLvJpA1tBXig=,tag:rCKshDyAbEWKFZU+cQKz9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q6l62kwaly44pl9vwedqvxtxv0fsndtq53s6kzclsccslne7cpfs2352vr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNHB6TGNjdlR6OFlmWG1s
            K0ZvK2hyUVRkU3QrenVIZWdZU21oYXUxa0FnCndNL3FpempsV0d5N3poMTFZdXRs
            N1FMT1pNQTcyeXY0bHRNQzliUUVyaXcKLS0tIGU0R1hRejAzT2hycEROb21MMWhL
            QktEZ2F3TlFaeXlLYXdJWURvaXpxNHMKKn+TZy2D4OxznFDETFXceZkcIq08IZpx
            cQqqNxGbiEgEc7Z3zen0ourv1xCFE9/+nDA2PEQVZUuElZCwyv21yA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-16T16:37:51Z"
    mac: ENC[AES256_GCM,data:udJ9IW3ixfIB5u7IuMt0XERUFIWkQ3LdHPab6qWo3ItaS78LpPsORSzUP2+4jNQXrbPQWuxpsKKJwPkA1hw0yD4ouvZ1KySmNGn04VHP3V6pR/bUXjg0kznJNdmZlzyOoXKk3LAMtwr+r+w7SM04J54+v5P92qduV6GtKfhW+t4=,iv:veSPVXdqJV2Um5V+FFmDyLDalH90VO+PAlFGP/ROX3U=,tag:oEMxP9T+fPQWUqlcKY69Hg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
