apiVersion: v1
kind: Secret
metadata:
    name: sensei-gatus-secrets
    namespace: default
# ## sops --encrypt --in-place ./kubernetes/apps/default/lldap/app/lldap.sops.yaml
# ## sops --decrypt ./kubernetes/apps/default/lldap/app/lldap.sops.yaml | kubectl apply -f -
stringData:
    #ENC[AES256_GCM,data:XExZzIk9iDMoO08G/oY=,iv:6LpcPktVtglrLKgnXPFStb/wtPm3PVN/cly5gqNUkVc=,tag:WYuq6k8miko8nLFkWN38yg==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:vgdgSHc=,iv:fpuHX2Q9IJIoSjAxgvkKLWo5DE+RLocovrrXhOX7wjI=,tag:uMNFc3ODBkMuPpQwbtv5/A==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:0//M2noMKSlphV/Ura1dQVijeDLhgz5wFdUXGWoGaOl8PdNPUQY1Ng==,iv:WD/rG2cYyUXUK4Gano2M+sa2cENfu9kjitDb04UwzT0=,tag:4Dxd47fPtnVf3i3zwL9DTQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:eLRo261i5YY=,iv:pGfC8ci+zU7ZSLDsEqNPXZHaZWj6CWoK0xsrrE8wJUQ=,tag:uhqAjGDXH0wf2YAZVeipDA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:G+IQL7LubtOg,iv:tWt8DUELK/UPGgzS2fZj9sqVusRhUKXcou4tbbtlvEg=,tag:2i7qMBdtqqpNCcgoVXN69A==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:GYomTExXqN9z,iv:P0o5RFHb48MZBr2zAW/XhKDPhWALgOTrLvJpA1tBXig=,tag:rCKshDyAbEWKFZU+cQKz9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q6l62kwaly44pl9vwedqvxtxv0fsndtq53s6kzclsccslne7cpfs2352vr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNHB6TGNjdlR6OFlmWG1s
            K0ZvK2hyUVRkU3QrenVIZWdZU21oYXUxa0FnCndNL3FpempsV0d5N3poMTFZdXRs
            N1FMT1pNQTcyeXY0bHRNQzliUUVyaXcKLS0tIGU0R1hRejAzT2hycEROb21MMWhL
            QktEZ2F3TlFaeXlLYXdJWURvaXpxNHMKKn+TZy2D4OxznFDETFXceZkcIq08IZpx
            cQqqNxGbiEgEc7Z3zen0ourv1xCFE9/+nDA2PEQVZUuElZCwyv21yA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-16T16:11:06Z"
    mac: ENC[AES256_GCM,data:3DzRw3ID8vTTvF5uQy9KDWh04KvQkkp5m+s0fBNxvPVPb3uT9DtvL/we7ABBPXlQWEA33/Qurv4XrpNSHKO7R9rWB+8qfprhDpjqJ633MDRTKUADoypSsZMV7adGYW9lnscXpF5tHLuRfHIuJirVbNGWK7abeyz3AJh8rEf+8ik=,iv:wkSmcu16c0v7w8OuHf9Hdn3dGGHH/ghN9MY8x/yNhkc=,tag:Yn4jVP4L6sXjP/Oyx/3MoQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
