---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gatus
  namespace: sensei
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: gatus
    meta.helm.sh/release-namespace: sensei
secrets:
  - name: gatus
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: gatus
  namespace: sensei
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: gatus
    meta.helm.sh/release-namespace: sensei
    kubernetes.io/service-account.name: gatus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gatus
  namespace: sensei
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gatus
  namespace: sensei
roleRef:
  kind: ClusterRole
  name: gatus
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: gatus
    namespace: sensei
