---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: listmonk
  namespace: sensei
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 2
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      listmonk:
        containers:
          app:
            image:
              repository: ghcr.io/knadh/listmonk
              tag: v5.1.0
            command: [sh, -c, "./listmonk --install --idempotent --yes --config '' && ./listmonk --upgrade --yes --config '' && ./listmonk --config ''"]
            env:
              LISTMONK_app__address: 0.0.0.0:9000
              LISTMONK_db__user: ${SECRET_PGADMIN_USER}
              LISTMONK_db__password: ${SECRET_PGADMIN_PASSWORD}
              LISTMONK_db__database: listmonk
              LISTMONK_db__host: postgres16vector-rw.database.svc.cluster.local
              LISTMONK_db__port: 5432
              LISTMONK_db__ssl_mode: disable
              LISTMONK_db__max_open: 25
              LISTMONK_db__max_idle: 25
              LISTMONK_db__max_lifetime: 300s
              TZ: America/New_York
              LISTMONK_ADMIN_USER: ${SECRET_LITELLM_UI_USERNAME}          # If these (optional) are set during the first `docker compose up`, then the Super Admin user is automatically created.
              LISTMONK_ADMIN_PASSWORD: ${SECRET_LITELLM_UI_PASSWORD}
            resources:
              requests:
                cpu: 5m
                memory: 128M
              limits:
                memory: 2G
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1025
        runAsGroup: 1025
        fsGroup: 1025
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: listmonk
        ports:
          http:
            port: 9000
    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN_TWO}"
          nginx.ingress.kubernetes.io/proxy-connect-timeout: "240"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "240"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "240"
          hajimari.io/enable: "true"
          hajimari.io/icon: mdi:water-flow
        className: external
        hosts:
          - host: listmonk.${SECRET_DOMAIN_TWO}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: 9000

    persistence:
      uploads:
        enabled: true
        type: nfs
        server: 192.168.1.3
        path: /volume1/network-storage/cluster/listmonk/uploads
        globalMounts:
          - path: /listmonk/uploads
