---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sensei-stage
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      sensei-stage:
        replicas: 1
        containers:
          sense_api:
            image:
              repository: ghcr.io/clarknova99/project-sensei/backend
              tag: 0.1.0@sha256:9b478a725913735d920b9adff1ae50ec639bfc2baab8cde45e93a205ed6bf23f
              pullPolicy: Always
            env:
              GROQ_API_KEY: ${SECRET_GROQ_API_KEY}
              PG_URI: postgresql://${SECRET_SENSEI_USERNAME}:${SECRET_SENSEI_PASSWORD}@192.168.3.41:5432/sensei-stage
          sense_app:
            image:
              repository: ghcr.io/clarknova99/project-sensei/frontend
              tag: 0.1.0@sha256:5ab563794ae395efced77ccdbe36e556ee080671a937a35348083d302ed187fa
              pullPolicy: Always
            env:
              API_HOST: sense_api.default
              PG_URI: postgresql://${SECRET_SENSEI_USERNAME}:${SECRET_SENSEI_PASSWORD}@192.168.3.41:5432/sensei-stage
        pod:
          # imagePullPolicy: Always
          imagePullSecrets:
            - name: sensei-secret            
    service:
      sense_api:
        controller: sensei-stage
        ports:
          http:
            port: 3001
      sense_app:
        controller: sensei-stage
        ports:
          http:
            port: 8501
    ingress:
      sense_api:
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN_TWO}"
          # nginx.ingress.kubernetes.io/auth-method: GET
          # nginx.ingress.kubernetes.io/auth-url: http://authelia.default.svc.cluster.local/api/verify
          # nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_DOMAIN_TWO}?rm=$request_method
          # nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
          # nginx.ingress.kubernetes.io/auth-snippet: proxy_set_header X-Forwarded-Method $request_method;
          hajimari.io/enable: "true"
          hajimari.io/icon: mdi:math-compass
        className: external
        hosts:
          - host: api-stage.${SECRET_DOMAIN_TWO}
            paths:
              - path: /
                service:
                  identifier: sense_api
                  port: 8501
        tls:
          - hosts:
              - api-stage.${SECRET_DOMAIN_TWO}
      sense_app:
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN_TWO}"
          hajimari.io/enable: "true"
          hajimari.io/icon: mdi:math-compass
        className: external
        hosts:
          - host: stage.${SECRET_DOMAIN_TWO}
            paths:
              - path: /
                service:
                  identifier: sense_app
                  port: 8501
        tls:
          - hosts:
              - stage.${SECRET_DOMAIN_TWO}              
