apiVersion: batch/v1
kind: CronJob
metadata:
  name: frigate-restart-deployment
spec:
  schedule: "0 */6 * * *"  # Runs every 6 hours
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kubectl
            image: bitnami/kubectl:latest
            command:
            - /bin/sh
            - -c
            - |
              kubectl delete pod -l app.kubernetes.io/name="frigate" -n default
          restartPolicy: OnFailure