apiVersion: v1
kind: Secret
metadata:
    name: rook-ceph-dashboard-password
## sops --encrypt --in-place ./kubernetes/apps/rook-ceph/rook-ceph/app/ceph.sops.yaml
## sops --decrypt ./kubernetes/apps/rook-ceph/rook-ceph/app/ceph.sops.yaml | kubectl apply -f -
stringData:
    password: ENC[AES256_GCM,data:vdFlOT5+f/Qd,iv:EA13+W6z8hMnpacc1I+lecjbZb6+STunf5c05IQYr9o=,tag:HRkhn4TzVal4QeM+foZrAg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q6l62kwaly44pl9vwedqvxtxv0fsndtq53s6kzclsccslne7cpfs2352vr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvUURYRGpycEFVclVsTTl4
            SndMa3ZGam9HVHZEbTlLamxZKzJjSk9QTkNJCmhwQWZsVm1tc2EyZ1RxS3g4aVZv
            ZUJPVHBHM3MzamVqM21WWTk1TXJTSUEKLS0tIEhwUHZQWS9BRlgvRWxJdnl2REVy
            TExSSTNXVjJuak95OTFaNFZIMEhuQ1UK+WGgrUID1FGqegMyoM2DFqoGOOHIiBgx
            wrNKabS7994K+HdWmzs0iCAOUWVrZ+cOLqw2n4oyt1G9TtkReoOY9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-29T14:55:01Z"
    mac: ENC[AES256_GCM,data:e8RigOxyYe9MkRsqgU79GXJQaG0af6+czSS+2r1JQV0/qrPl+rl8q4iWAnjwHawPRAx4Vnw9s+qNuEbmzCX9ZaGhaGVrGayjeIHowNOhgF+5Sm1+4/naJzzztjNhL8dcR5QyuOiZFlQGLcVyB8eFwwuFYAsl4G8hFddnh40GzyQ=,iv:wlbCioiV1EiOPwEeES4AOfn/3w3izFN0lst5RpxYhJQ=,tag:HuRzbqEJ4i4n0RqaNBM1xg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
