---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: chronograf
  namespace: database
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      chronograf:
        replicas: 1
        containers:
          app:
            image:
              repository: docker.io/chronograf
              tag: 1.9.4-alpine
    service:
      app:
        controller: chronograf
        ports:
          http:
            port: 8888
    ingress:
      app:
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: mdi:ip-network
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
          nginx.ingress.kubernetes.io/ssl-redirect: "false"
          ingress.kubernetes.io/proxy-ssl-verify: "off"
          ingress.kubernetes.io/force-ssl-redirect: "false"
          ingress.kubernetes.io/ssl-redirect: "false"          
        className: internal
        hosts:
          - host: chronograf.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: 8888
        tls:
          - hosts:
              - chronograf.${SECRET_DOMAIN}

    persistence:
      config:
        enabled: true
        type: nfs
        server: 192.168.1.2
        path: /volume1/network-storage/chronograf
        globalMounts:
          - path: /var/lib/chronograf