apiVersion: v1
kind: Secret
metadata:
    name: gatus-dittofeed-check-secrets
    namespace: observability
## sops --encrypt --in-place ./kubernetes/apps/observability/gatus/cronjob/cronjob.sops.yaml
## sops --decrypt ./kubernetes/apps/observability/gatus/cronjob/cronjob.sops.yaml | kubectl apply -f -
stringData:
    CLICKHOUSE_PASSWORD: ENC[AES256_GCM,data:RhOQfle5r1ycwdIkiIU2X9rOosOjtM2q/jQkAj4=,iv:M2e6Bso7nZy3wEzws0ljL7WtK6gvopPJqzmrNnvDNgY=,tag:EW9ZGqeLjLDY0Q+3NVJzMg==,type:str]
    GATUS_TOKEN: ENC[AES256_GCM,data:0IjR7UKo9r5ZqEBH1uR8b9wRxTljuCGaYAJoA2Y2t7N2w4G9mIqjHzzcZGz2nX/1dQpqHQLJ4Alq4qgwofBm9A==,iv:SF2M8Um2yltDkfyRRNKF6/PhMl1wFphL+0PVB8IVvDw=,tag:3zkXAAOIzAS8L4iCAOtG+g==,type:str]
sops:
    age:
        - recipient: age1q6l62kwaly44pl9vwedqvxtxv0fsndtq53s6kzclsccslne7cpfs2352vr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZk1lS2ZwV0hOcnkrT1kx
            WFBuMmgxb2puZDJMUE11M29EZnFXS2J6cHlVClRhc1dubzFKVlcwUU9qTEozU3Fu
            Y1ZxZ1VoSE5OYjA1emVJL3JnS05FWXcKLS0tIFpCVjZ2RXBrTWlZRVRSTmVUYzNi
            QzVUTE5oT2U0UWZsd000c0ZYSmNSSEUKc8GX89I5s8t/alyE5mEbQArr10VAFMBt
            ks5KTaPY1btRkBB6yzPnKYTUTWrz4HHi6u+SeTby/TRlPxWEoISI7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T17:18:09Z"
    mac: ENC[AES256_GCM,data:eEqYxRZie8OyRIszncFrYUZTk6PJpiOlnALJiFGsC3U/MGNuSPnVe2PwRqbu7rA+tqnk5eaz4Hdl3nnl6VsO9xh6VuwSrcjjYG6JFkCdkabAjsTsiSo3L4Ca5EbDrl44sZnTJZK7V5Q05LJrQP8vQmrbRYqZ7/3R7sx+tx3ky3M=,iv:CtTsTSaerOFQqFX2D9GQpHYLyWoZE9rE2bfiMsVa3nE=,tag:rOMGu0ZMsvFHZ13LXkWACA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
