---

logger:
  default: info
  # logs:
  #   frigate.record: debug
  #   frigate.record.maintainer: debug
  #   frigate.video: debug

  #   ffmpeg.frontyard_hq: error
  #   ffmpeg.backyard_hq: error
  #   #frigate.ptz.onvif: debug

mqtt:
  host: mosquitto.default.svc.cluster.local
  topic_prefix: frigate
  # user: "${SECRET_MQTT_USERNAME}"
  # password: "${SECRET_MQTT_PASSWORD}"

database:
  path: /data/frigate.db

ffmpeg:
  global_args: ["-hide_banner", "-loglevel", "warning"]
  hwaccel_args: preset-intel-qsv-h264

detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  frontyard:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy     
      inputs:
        - path: rtsp://${SECRET_CAM_USERNAME}:${SECRET_CAM_PASSWORD}@192.168.1.101:554/stream2#timeout=20
          roles:
            - detect
        - path: rtsp://${SECRET_CAM_USERNAME}:${SECRET_CAM_PASSWORD}@192.168.1.101:554/stream1#timeout=20 
          roles:
            - record
  frontdoor:
    ffmpeg:  
      hwaccel_args: preset-intel-qsv-h265
      output_args:
        record: preset-record-generic-audio-copy     
      inputs:
        - path: ffmpeg:rtsp://${SECRET_BACKYARDCAM_USERNAME}:${SECRET_BACKYARDCAM_PASSWORD}@192.168.1.146:554/ch0_0.264#timeout=20#video=h264
          roles:
            - detect
        - path: ffmpeg:rtsp://${SECRET_BACKYARDCAM_USERNAME}:${SECRET_BACKYARDCAM_PASSWORD}@192.168.1.146:554/ch0_1.264#timeout=20#video=h264
          roles:
            - record            
  backyard:
    ffmpeg:  
      output_args:
        record: preset-record-generic-audio-copy     
      inputs:
        - path: rtsp://${SECRET_BACKYARDCAM_USERNAME}:${SECRET_WIFICAM_PASSWORD}@192.168.1.201:10554/tcp/av0_1#timeout=20
          roles:
            - detect
        - path: rtsp://${SECRET_BACKYARDCAM_USERNAME}:${SECRET_WIFICAM_PASSWORD}@192.168.1.201:10554/tcp/av0_0#timeout=20
          roles:
            - record    