---
name: "Download kromgo badges"

on:
  workflow_dispatch:
  schedule: 
    - cron: "0 */6 * * *"

jobs:
  render-readme:
    name: Download kromgo badges
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5
        with:
          python-version: 3.x
          cache: pip

      - name: Install Python Requirements
        shell: bash
        run: pip install requests==2.32.3

      - name: Debug network
        shell: bash
        run: |
          echo "Testing domain resolution..."
          nslookup kromgo.${{ secrets.SECRET_DOMAIN }} || echo "Failed to resolve domain"
          echo "Testing connection..."
          curl -I https://kromgo.${{ secrets.SECRET_DOMAIN }}/talos_version || echo "Failed to connect"

      - name: Download kromgo badges
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          SECRET_DOMAIN: "${{ secrets.SECRET_DOMAIN }}"
        shell: bash
        run: python ./.github/scripts/kromgo-badges.py

      - name: Commit Changes
        shell: bash
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ./kromgo
          git commit -m "chore: download kromgo badges" || echo "No changes to commit"
          git push origin || echo "No changes to push"